//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Labels", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستوى السرية.
        /// </summary>
        internal static string Confidentiality_AR {
            get {
                return ResourceManager.GetString("Confidentiality_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستقبال.
        /// </summary>
        internal static string DeptReception {
            get {
                return ResourceManager.GetString("DeptReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد.
        /// </summary>
        internal static string Inbound_AR {
            get {
                return ResourceManager.GetString("Inbound_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور المعاملات.
        /// </summary>
        internal static string InobundCopies_AR {
            get {
                return ResourceManager.GetString("InobundCopies_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور الصادر.
        /// </summary>
        internal static string OutboundCopies_AR {
            get {
                return ResourceManager.GetString("OutboundCopies_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشروع صادر.
        /// </summary>
        internal static string Outbound_AR {
            get {
                return ResourceManager.GetString("Outbound_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموعد.
        /// </summary>
        internal static string PriorityDate_AR {
            get {
                return ResourceManager.GetString("PriorityDate_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الأسبقية.
        /// </summary>
        internal static string Priority_AR {
            get {
                return ResourceManager.GetString("Priority_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للإطلاع.
        /// </summary>
        internal static string ReadOnly_AR {
            get {
                return ResourceManager.GetString("ReadOnly_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        internal static string Subject_AR {
            get {
                return ResourceManager.GetString("Subject_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        internal static string Type_AR {
            get {
                return ResourceManager.GetString("Type_AR", resourceCulture);
            }
        }
    }
}
