//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutMorasalat_AR {
            get {
                return ResourceManager.GetString("AboutMorasalat_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutMorasalat_EN {
            get {
                return ResourceManager.GetString("AboutMorasalat_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContactUs_AR {
            get {
                return ResourceManager.GetString("ContactUs_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContactUs_EN {
            get {
                return ResourceManager.GetString("ContactUs_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string CopiesDashboardLabel_AR {
            get {
                return ResourceManager.GetString("CopiesDashboardLabel_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        internal static string CopiesDashboardLabel_EN {
            get {
                return ResourceManager.GetString("CopiesDashboardLabel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرجاع المعاملة بشكل صحيح.
        /// </summary>
        internal static string CorrespondenceGetSuccessful_AR {
            get {
                return ResourceManager.GetString("CorrespondenceGetSuccessful_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was retrieved correctly.
        /// </summary>
        internal static string CorrespondenceGetSuccessful_EN {
            get {
                return ResourceManager.GetString("CorrespondenceGetSuccessful_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم استرجاع المعاملة بشكل صحيح.
        /// </summary>
        internal static string CorrespondenceGetUnsuccessful_AR {
            get {
                return ResourceManager.GetString("CorrespondenceGetUnsuccessful_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was not retrieved correctly.
        /// </summary>
        internal static string CorrespondenceGetUnsuccessful_EN {
            get {
                return ResourceManager.GetString("CorrespondenceGetUnsuccessful_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة غير صحيح.
        /// </summary>
        internal static string CorrespondenceIdNotValid_AR {
            get {
                return ResourceManager.GetString("CorrespondenceIdNotValid_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction number is not valid.
        /// </summary>
        internal static string CorrespondenceIdNotValid_EN {
            get {
                return ResourceManager.GetString("CorrespondenceIdNotValid_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استرجاع قائمة المعاملات بنجاح.
        /// </summary>
        internal static string CorrespondencesReturnedSuccessfully_AR {
            get {
                return ResourceManager.GetString("CorrespondencesReturnedSuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of transcations are retrieved successfully.
        /// </summary>
        internal static string CorrespondencesReturnedSuccessfully_EN {
            get {
                return ResourceManager.GetString("CorrespondencesReturnedSuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات المعاملة بنجاح.
        /// </summary>
        internal static string CorrespondenceUpdatedSuccessfully_AR {
            get {
                return ResourceManager.GetString("CorrespondenceUpdatedSuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was updated successfully.
        /// </summary>
        internal static string CorrespondenceUpdatedSuccessfully_EN {
            get {
                return ResourceManager.GetString("CorrespondenceUpdatedSuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in saving the transaction.
        /// </summary>
        internal static string CorrespondenceUpdatedUnsuccessfully_AR {
            get {
                return ResourceManager.GetString("CorrespondenceUpdatedUnsuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حصل خطأ في حفظ المعاملة.
        /// </summary>
        internal static string CorrespondenceUpdatedUnsuccessfully_EN {
            get {
                return ResourceManager.GetString("CorrespondenceUpdatedUnsuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ في العملية.
        /// </summary>
        internal static string DataNotReturned_AR {
            get {
                return ResourceManager.GetString("DataNotReturned_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not done successfully.
        /// </summary>
        internal static string DataNotReturned_EN {
            get {
                return ResourceManager.GetString("DataNotReturned_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        internal static string DataReturnedSuccessfully_AR {
            get {
                return ResourceManager.GetString("DataReturnedSuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation done successfully.
        /// </summary>
        internal static string DataReturnedSuccessfully_EN {
            get {
                return ResourceManager.GetString("DataReturnedSuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتأخرة.
        /// </summary>
        internal static string DelayedTransactionsDashboardLabel_AR {
            get {
                return ResourceManager.GetString("DelayedTransactionsDashboardLabel_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delayed.
        /// </summary>
        internal static string DelayedTransactionsDashboardLabel_EN {
            get {
                return ResourceManager.GetString("DelayedTransactionsDashboardLabel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الوثيقة غير صحيحة.
        /// </summary>
        internal static string DocumentDataInvalid_AR {
            get {
                return ResourceManager.GetString("DocumentDataInvalid_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document data is invalid.
        /// </summary>
        internal static string DocumentDataInvalid_EN {
            get {
                return ResourceManager.GetString("DocumentDataInvalid_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هـ.
        /// </summary>
        internal static string HijriSymbol_AR {
            get {
                return ResourceManager.GetString("HijriSymbol_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        internal static string HijriSymbol_EN {
            get {
                return ResourceManager.GetString("HijriSymbol_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير صحيحة.
        /// </summary>
        internal static string IncorrectSignaturePassword_AR {
            get {
                return ResourceManager.GetString("IncorrectSignaturePassword_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password.
        /// </summary>
        internal static string IncorrectSignaturePassword_EN {
            get {
                return ResourceManager.GetString("IncorrectSignaturePassword_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدخول غير صحيح.
        /// </summary>
        internal static string InvalidUserName_AR {
            get {
                return ResourceManager.GetString("InvalidUserName_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name.
        /// </summary>
        internal static string InvalidUserName_EN {
            get {
                return ResourceManager.GetString("InvalidUserName_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الدخول بنجاح.
        /// </summary>
        internal static string LoginSuccessfully_AR {
            get {
                return ResourceManager.GetString("LoginSuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully.
        /// </summary>
        internal static string LoginSuccessfully_EN {
            get {
                return ResourceManager.GetString("LoginSuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الخروج بنجاح.
        /// </summary>
        internal static string LogoutSuccessfully_AR {
            get {
                return ResourceManager.GetString("LogoutSuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was unsuccessful.
        /// </summary>
        internal static string LogoutSuccessfully_EN {
            get {
                return ResourceManager.GetString("LogoutSuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الخروج بنجاح.
        /// </summary>
        internal static string LogoutUnsuccessfully_AR {
            get {
                return ResourceManager.GetString("LogoutUnsuccessfully_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout was successful.
        /// </summary>
        internal static string LogoutUnsuccessfully_EN {
            get {
                return ResourceManager.GetString("LogoutUnsuccessfully_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملاتي.
        /// </summary>
        internal static string MyTransactionsDashboardLabel_AR {
            get {
                return ResourceManager.GetString("MyTransactionsDashboardLabel_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transactions.
        /// </summary>
        internal static string MyTransactionsDashboardLabel_EN {
            get {
                return ResourceManager.GetString("MyTransactionsDashboardLabel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد كلمة مرور على التوقيع.
        /// </summary>
        internal static string NoSignaturePasswordExist_AR {
            get {
                return ResourceManager.GetString("NoSignaturePasswordExist_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature passoword exist.
        /// </summary>
        internal static string NoSignaturePasswordExist_EN {
            get {
                return ResourceManager.GetString("NoSignaturePasswordExist_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session token timed out. Please log in once again.
        /// </summary>
        internal static string SessionTokenTimedOut_AR {
            get {
                return ResourceManager.GetString("SessionTokenTimedOut_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session token timed out. Please log in once again.
        /// </summary>
        internal static string SessionTokenTimedOut_EN {
            get {
                return ResourceManager.GetString("SessionTokenTimedOut_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndConditions_AR {
            get {
                return ResourceManager.GetString("TermsAndConditions_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  تعهد الالتزام بالاستخدام المقبول والخصوصية
        ///
        ///1. يتعهد الموظف اتعهد بعدم مشاركة أي معلومات مملوكة للهيئة بأي شكل من الأشكال
        ///مع أي طرف ثالث إلا بموافقة كتابية من الهيئة.
        ///2. يتعهد الموظف اتعهد بعدم محاولة الوصول لأي معلومات مملوكة للهيئة وتقع خارج
        ///نطاق عملهي وبإعلام الهيئة في حال تحقق ذلك.
        ///3. يلتزم الموظف التزم بإعلام واخطار الهيئة عن أي حالة تسرب لمعلومات مملوكة لها
        ///لدى طرف ثالث.
        ///4. يتعهد الموظف عند انتهاء العلاقة، اتعهد بإعادة جميع المعلومات الرقمية وغير الرقمية
        ///للهيئة وإتلاف جميع المعلومات الأخرى وا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndConditions_EN {
            get {
                return ResourceManager.GetString("TermsAndConditions_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك استخدام النظام من خلال التطبيق.
        /// </summary>
        internal static string UnauthenticatedUserOniPad_AR {
            get {
                return ResourceManager.GetString("UnauthenticatedUserOniPad_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use the system via this app.
        /// </summary>
        internal static string UnauthenticatedUserOniPad_EN {
            get {
                return ResourceManager.GetString("UnauthenticatedUserOniPad_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم/كلمة السر غير صحيحة.
        /// </summary>
        internal static string UnauthenticatedUser_AR {
            get {
                return ResourceManager.GetString("UnauthenticatedUser_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name/password is incorrect.
        /// </summary>
        internal static string UnauthenticatedUser_EN {
            get {
                return ResourceManager.GetString("UnauthenticatedUser_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم مربوط بجهاز آي باد آخر.
        /// </summary>
        internal static string UserConnectedToAnotheriPad_AR {
            get {
                return ResourceManager.GetString("UserConnectedToAnotheriPad_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is already linked to another iPad.
        /// </summary>
        internal static string UserConnectedToAnotheriPad_EN {
            get {
                return ResourceManager.GetString("UserConnectedToAnotheriPad_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيها موعد.
        /// </summary>
        internal static string WithAppointmentTransactionsDashboardLabel_AR {
            get {
                return ResourceManager.GetString("WithAppointmentTransactionsDashboardLabel_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Appointment.
        /// </summary>
        internal static string WithAppointmentTransactionsDashboardLabel_EN {
            get {
                return ResourceManager.GetString("WithAppointmentTransactionsDashboardLabel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت لم تسجل عملية الدخول الى الخدمة.
        /// </summary>
        internal static string YouAreNotLoggedIn_AR {
            get {
                return ResourceManager.GetString("YouAreNotLoggedIn_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in to the service.
        /// </summary>
        internal static string YouAreNotLoggedIn_EN {
            get {
                return ResourceManager.GetString("YouAreNotLoggedIn_EN", resourceCulture);
            }
        }
    }
}
