//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceHelp", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على نسخة من المعاملات (غير قابلة للتعديل) وذلك لتمكين الموظف من الاطلاع عليها بناء على الصلاحيات الممنوحة له. حيث يحتوي هذا الصندوق على المعاملات التالية:&lt;/p&gt;
        ///&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;نسخ المعاملات الداخلية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;نسخ المعاملات الخارجية.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق النسخ الإلكترونية، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Copies_Body {
            get {
                return ResourceManager.GetString("File_Copies_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق النسخ الإلكترونية.
        /// </summary>
        internal static string File_Copies_Title {
            get {
                return ResourceManager.GetString("File_Copies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المعاملات التي قيد التصدير (مسودة خطاب) بالإضافة إلى احتوائه على نسخ من جميع معاملات الصادر التي تم تصديرها من قبل الموظف. حيث يحتوي هذا الصندوق على المعاملات التالية:&lt;/p&gt;
        ///&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;المعاملات التي قيد التصدير.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;المعاملات الصادر التي قام الموظف بتصديرها.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المعاملات الصادرة، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_DraftOutbound_Body {
            get {
                return ResourceManager.GetString("File_DraftOutbound_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المعاملات الصادرة.
        /// </summary>
        internal static string File_DraftOutbound_Title {
            get {
                return ResourceManager.GetString("File_DraftOutbound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على نسخ من المعاملات التي تمت متابعتها من قبل الموظف أو التي تم إضافة متابعة للموظف عليها من قبل موظف آخر وذلك لمراجعتها واستعراض بياناتها. &lt;/p&gt;
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المتابعة، قم بالتالي:&lt;/p&gt;
        ///
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على القائمة الفرعية &quot;المتابعة&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض نسخ المعاملات التي تم إضافة متابعة عليها على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طري [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_FollowUp_Body {
            get {
                return ResourceManager.GetString("File_FollowUp_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المتابعة.
        /// </summary>
        internal static string File_FollowUp_Title {
            get {
                return ResourceManager.GetString("File_FollowUp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على معاملات موظفي الوحدة الإدارية في صندوق معاملاتي فقط، وذلك لتمكين مدير الإدارة من اتخاذ إجراء على تلك المعاملات دون الرجوع للموظف. &lt;/p&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المدير، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على القائمة الفرعية &quot;المدير&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات مع على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طريقة عرض المعاملات من خلال اضغط على زر  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Manager_Body {
            get {
                return ResourceManager.GetString("File_Manager_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المدير.
        /// </summary>
        internal static string File_Manager_Title {
            get {
                return ResourceManager.GetString("File_Manager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;&lt;span&gt;يحتوي هذا الصندوق على المعاملات&lt;/span&gt;&lt;span&gt; الواردة والمعاملات الداخلية&lt;/span&gt;&lt;span&gt; التي يجب على المستخدم العمل عليها وإنجازها والمعاملات المتأخرة التي لم يتم العمل عليها خلال مدة محددة والمعاملات التي يجب تسليمها في موعد محدد. حيث يحتوي هذا الصندوق على المعاملات التالية:&lt;/span&gt;&lt;/p&gt;
        ///&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;المعاملات المحالة إلى الموظف.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;المعاملات التي قام باستلامها من &lt;/span&gt;&lt;span&gt;صندوق استقبال الإدارة &lt;/span&gt;&lt;span&gt;الخاص بإدارة الموظف.&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_MyTransaction_Body {
            get {
                return ResourceManager.GetString("File_MyTransaction_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق معاملاتي.
        /// </summary>
        internal static string File_MyTransaction_Title {
            get {
                return ResourceManager.GetString("File_MyTransaction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المعاملات التي أرسلت للإدارة التي يعمل بها الموظف، حيث يظهر لجميع الموظفين الذين يعملون بهذه الإدارة.&lt;/p&gt;
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى هذا الصندوق، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot; استقبال الإدارة&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طريقة عرض المعاملات من خلال الضغط على زر &quot; جدول&quot; لعرض المعاملات على شكل قائمة في جدول.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ol&gt;
        ///&lt;p class=&quot;block_text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_OrgUnit_Body {
            get {
                return ResourceManager.GetString("File_OrgUnit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق استقبال الإدارة.
        /// </summary>
        internal static string File_OrgUnit_Title {
            get {
                return ResourceManager.GetString("File_OrgUnit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span&gt;تم إنشاء خاصية &lt;/span&gt;&lt;span&gt; حجز المعاملات في النظام بهدف الحفاظ على تسلسل أرقام المعاملات وتاريخ الإنشاء. ويتم تطبيق هذه الخاصية فقط على معاملات الصادر الخارجي والوارد الخارجي.&lt;/span&gt;&lt;/p&gt;
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى شاشة الحجز، قم بالتالي:&lt;/p&gt;
        ///
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختيار صندوق المعاملات المحجوزة من القائمة الجانبية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات المحجوزة وعرض المعاملات المحجوزة على شكل بطاقات أو ج [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Reservation_Body {
            get {
                return ResourceManager.GetString("File_Reservation_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجز المعاملات.
        /// </summary>
        internal static string File_Reservation_Title {
            get {
                return ResourceManager.GetString("File_Reservation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المعاملات التي تم الانتهاء من العمل عليها مستوى الإدارة لحفظها.&lt;/p&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المنجزة، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات المنجزة &quot;&lt;/span&gt; &lt;span&gt;من القائمة الفرعية. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات المنجزة مع عرض سبب حفظها كمنجزة، على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طريقة عرض المعاملات من خلال الضغط على زر &quot;ج [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Saved_Body {
            get {
                return ResourceManager.GetString("File_Saved_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المنجزة.
        /// </summary>
        internal static string File_Saved_Title {
            get {
                return ResourceManager.GetString("File_Saved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المعاملات التي تم إحالتها داخليا من قبل الموظف والتي لم يتم استلامها من قبل الجهة أو الموظف المحالة لهم. &lt;/p&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المعاملات المرسلة، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt; اضغط على القائمة الفرعية &quot;المعاملات المرسلة&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات المرسلة مع على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طريقة عرض المعاملات من خلال الضغط ع [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_SentTransactions_Body {
            get {
                return ResourceManager.GetString("File_SentTransactions_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المعاملات المرسلة .
        /// </summary>
        internal static string File_SentTransactions_Title {
            get {
                return ResourceManager.GetString("File_SentTransactions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المهامالتي قيد الاستلاموالتي تم قبول استلامها وذلك للعمل عليها لإكمال إنجاز المعاملة، حيث يحتوي هذا الصندوق على المهام التالية:&lt;/p&gt;
        ///&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;المهام المرسلة إلى الموظف والتي تم قبولها.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;المهام المرسلة إلى الموظف والتي ما زالت قيد الاستلام.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ul&gt;
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى صندوق المهام، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string File_Tasks_Body {
            get {
                return ResourceManager.GetString("File_Tasks_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المهام.
        /// </summary>
        internal static string File_Tasks_Title {
            get {
                return ResourceManager.GetString("File_Tasks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تمكن هذه خاصية المستخدم من استقبال وعرض التنبيهات التي يرسلها النظام.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-135&quot; class=&quot;sub_title&quot;&gt;عرض التنبيهات&lt;/h2&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;التنبيهات&quot; الموجود في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم لشاشة التنبيهات.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بعرض التنبيهات في جدول. (ستكون التنبيهات الجديدة مميزه عن التنبيهات القديمة)&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        internal static string Home_AllNotification_Body {
            get {
                return ResourceManager.GetString("Home_AllNotification_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنبيهات.
        /// </summary>
        internal static string Home_AllNotification_Title {
            get {
                return ResourceManager.GetString("Home_AllNotification_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يحتوي هذا الصندوق على المعاملات والنسخ الإلكترونية التي تم إرسالها إلكترونيا من الجهات الخارجية المسجلة في نظام مراسلات الوطني. &lt;/p&gt;
        ///
        ///
        ///&lt;p class=&quot;block_text&quot;&gt;للوصول إلى هذا الصندوق، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على زر &quot; المعاملات&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اضغط على القائمة الفرعية &quot;&lt;/span&gt;&lt;span&gt;المعاملات والنسخ المستلمة من الجهات الخارجية&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض المعاملات مع على شكل بطاقات بشكل تلقائي، حيث يمكنك تغيير طريقة عرض ال [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hub_GetAll_Body {
            get {
                return ResourceManager.GetString("Hub_GetAll_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق المعاملات والنسخ المستلمة من الجهات الخارجية.
        /// </summary>
        internal static string Hub_GetAll_Title {
            get {
                return ResourceManager.GetString("Hub_GetAll_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يقوم المستخدم من خلال هذه الجزئية بإنشاء معاملة وارد من جهات خارجية وإحالتها بين إدارات الجهة الداخلية أو المستخدمين داخل الإدارات كما يلي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;إنشاء وارد جديد من خلال الضغط على &quot;إنشاء وارد&quot; &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;تعبئة البيانات الأساسية، حيث تمثل الحقول المعنونة &lt;/span&gt;&lt;span class=&quot;text_9&quot;&gt;*&lt;/span&gt;&lt;span class=&quot;text_10&quot;&gt;حقول إجبارية لا يمكن إنشاء وارد دون إتمام إدخالها.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;تحديد الإدارة المختصة من البيانات الأساسية في حق [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inbound_Add_Body {
            get {
                return ResourceManager.GetString("Inbound_Add_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء وارد جديد.
        /// </summary>
        internal static string Inbound_Add_Title {
            get {
                return ResourceManager.GetString("Inbound_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تحتوي الصناديق الخاصة بالمعاملات على المعاملات التي قام المستخدم بإنشائها أو استلامها ويمكن للمستخدم أن يقوم بتحرير تلك المعاملات واتخاذ الإجراء اللازم عليها كما يلي:&lt;/p&gt;
        ///&lt;p class=&quot;block_textc underline_text&quot;&gt;للوصول إلى المعاملات في صندوق معاملاتي قم بما يلي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على &quot;المعاملات&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم إلى صندوق معاملاتي.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;قم بالضغط على زر &quot;تعديل&quot; في بطاقة المعاملة.&lt;/span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Inbound_Edit_Body {
            get {
                return ResourceManager.GetString("Inbound_Edit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل معاملة الوارد.
        /// </summary>
        internal static string Inbound_Edit_Title {
            get {
                return ResourceManager.GetString("Inbound_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 id=&quot;calibre_link-7&quot; class=&quot;sub_title&quot;&gt;إنشاء صادر خارجي جديد&lt;/h2&gt;
        ///	&lt;p class=&quot;block_text&quot;&gt;في هذا الجزء من وحدة إنشاء الصادر الخارجي وصف للإجراءات والنشاطات التي يجب إتباعها عند إدخال بيانات المعاملة الصادرة الموجهة إلى جهات خارجية لذا سيقوم الموظف بإنشاء معاملة صادر خارجي بعد تحديد نوع الصادر قبل إدخالها&lt;span &gt; في نظام مراسلات المركزي من خلال جزئية إنشاء الصادر، ولإنشاء صادر خارجي جديد إتباع الخطوات التالي:  &lt;/span&gt;&lt;/p&gt;
        ///	&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;إنشاء صادر جديد من خلال الضغط على &quot;إنشاء  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundExternal_Add_Body {
            get {
                return ResourceManager.GetString("OutboundExternal_Add_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء صادر خارجي جديد و إنشاء مسودة خطاب صادر جديد.
        /// </summary>
        internal static string OutboundExternal_Add_Title {
            get {
                return ResourceManager.GetString("OutboundExternal_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;في هذا الجزء من وحدة إنشاء الصادر الخارجي وصف للإجراءات والنشاطات التي يجب إتباعها عند إدخال بيانات المعاملة الصادرة الموجهة إلى جهات خارجية لذا سيقوم الموظف بإنشاء معاملة صادر خارجي بعد تحديد نوع الصادر قبل إدخالها&lt;span &gt; في نظام مراسلات المركزي من خلال جزئية إنشاء الصادر، ولإنشاء صادر خارجي جديد إتباع الخطوات التالي:  &lt;/span&gt;&lt;/p&gt;
        ///	&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;إنشاء صادر جديد من خلال الضغط على &quot;إنشاء صادر &quot; &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;تعبئة البيانات الأساسية، حيث تمثل الحقو [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundExternal_CreateOutbound_Body {
            get {
                return ResourceManager.GetString("OutboundExternal_CreateOutbound_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء صادر خارجي جديد من مسودة الخطاب.
        /// </summary>
        internal static string OutboundExternal_CreateOutbound_Title {
            get {
                return ResourceManager.GetString("OutboundExternal_CreateOutbound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تحتوي الصناديق الخاصة بالمعاملات على المعاملات التي قام المستخدم بإنشائها أو استلامها ويمكن للمستخدم أن يقوم بتحرير تلك المعاملات واتخاذ الإجراء اللازم عليها كما يلي:&lt;/p&gt;
        ///&lt;p class=&quot;block_textc underline_text&quot;&gt;للوصول إلى المعاملات في صندوق معاملاتي قم بما يلي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على &quot;المعاملات&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم إلى صندوق معاملاتي.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;قم بالضغط على زر &quot;تعديل&quot; في بطاقة المعاملة.&lt;/span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundExternal_Edit_Body {
            get {
                return ResourceManager.GetString("OutboundExternal_Edit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صادر خارجي او تعديل مسودة الخطاب.
        /// </summary>
        internal static string OutboundExternal_Edit_Title {
            get {
                return ResourceManager.GetString("OutboundExternal_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يقوم المستخدم من خلال هذه الجزئية بإنشاء معاملة داخلية وإحالتها بين إدارات الجهة الداخلية أو المستخدمين داخل الإدارات كما يلي:&lt;/p&gt;
        ///
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر إنشاء معاملة.&lt;/span&gt; &lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;تعبئة البيانات الأساسية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;إدخال الجهة التي سيتم إحالة المعاملة لها &quot;محالة إلى&quot; من البيانات الأساسية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;إضافة خطاب أصل المعاملة من خلال ما يلي:&lt;/span&gt;
        ///	&lt;ol&gt;
        ///		&lt;li&gt;&lt;span&gt;إدخال الخطاب عن طريق معالج النصوص من خلال كتابة [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundInternal_Add_Body {
            get {
                return ResourceManager.GetString("OutboundInternal_Add_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء معاملة داخلية.
        /// </summary>
        internal static string OutboundInternal_Add_Title {
            get {
                return ResourceManager.GetString("OutboundInternal_Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;يقوم المستخدم من خلال هذه الجزئية بإنشاء معاملة داخلية وإحالتها بين إدارات الجهة الداخلية أو المستخدمين داخل الإدارات كما يلي:&lt;/p&gt;
        ///
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر إنشاء معاملة داخل صندوق النسخ.&lt;/span&gt; &lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;تعبئة البيانات الأساسية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;إدخال الجهة التي سيتم إحالة المعاملة لها &quot;محالة إلى&quot; من البيانات الأساسية.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;إضافة خطاب أصل المعاملة من خلال ما يلي:&lt;/span&gt;
        ///	&lt;ol&gt;
        ///		&lt;li&gt;&lt;span&gt;إدخال الخطاب عن طريق معالج الن [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundInternal_CreateCopyOutboundInternal_Body {
            get {
                return ResourceManager.GetString("OutboundInternal_CreateCopyOutboundInternal_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء معاملة داخلية من نسخه الكترونيه.
        /// </summary>
        internal static string OutboundInternal_CreateCopyOutboundInternal_Title {
            get {
                return ResourceManager.GetString("OutboundInternal_CreateCopyOutboundInternal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تحتوي الصناديق الخاصة بالمعاملات على المعاملات التي قام المستخدم بإنشائها أو استلامها ويمكن للمستخدم أن يقوم بتحرير تلك المعاملات واتخاذ الإجراء اللازم عليها كما يلي:&lt;/p&gt;
        ///&lt;p class=&quot;block_textc underline_text&quot;&gt;للوصول إلى المعاملات في صندوق معاملاتي قم بما يلي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على &quot;المعاملات&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم إلى صندوق معاملاتي.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;قم بالضغط على زر &quot;تعديل&quot; في بطاقة المعاملة.&lt;/span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OutboundInternal_Edit_Body {
            get {
                return ResourceManager.GetString("OutboundInternal_Edit_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل معاملة داخلية.
        /// </summary>
        internal static string OutboundInternal_Edit_Title {
            get {
                return ResourceManager.GetString("OutboundInternal_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة تقارير قياس الادء.
        /// </summary>
        internal static string Reports_PerformanceMeasurementReport_Body {
            get {
                return ResourceManager.GetString("Reports_PerformanceMeasurementReport_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير قياس الاداء.
        /// </summary>
        internal static string Reports_PerformanceMeasurementReport_Title {
            get {
                return ResourceManager.GetString("Reports_PerformanceMeasurementReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تختص هذه الجزئية بعمليات البحث المختلفة كما ويمكن من خلالها طباعة تقرير البحث، حيث يستطيع المستخدم أن يصل إلى هذه الصفحة من خلال الصفحة الرئيسية في النظام عن طريق الضغط على تبويب &quot;البحث والتقارير&quot;. &lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li class=&quot;block_title2&quot;&gt;&lt;span&gt;البحث وتقارير المعاملات: يقوم المستخدم بالبحث عن المعاملات وطباعة تقرير لنتائج البحث:&lt;/span&gt;&lt;/li&gt;
        ///
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على تبويب &quot;البحث والتقارير&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختيار &quot; البحث وتقاري [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reports_TransactionReport_Body {
            get {
                return ResourceManager.GetString("Reports_TransactionReport_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث والتقارير.
        /// </summary>
        internal static string Reports_TransactionReport_Title {
            get {
                return ResourceManager.GetString("Reports_TransactionReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تحتوي هذه الجزئية على بيانات تسليم المعاملات التي قام المستخدم بإنشائها أو إحالتها من جميع أنواع المعاملات في النظام. كما يمكن للمستخدم من خلالها أرشفة بيانات التسليم بعد توقيعها.&lt;/p&gt;
        ///&lt;p class=&quot;block_text underline_text&quot;&gt;للوصول إلى جزئية بيانات التسليم قم بما يلي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على تبويب &quot;بيانات التسليم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار شاشة بيانات التسليم.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ol&gt;
        ///		&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reports_TransactionsDeliveryReport_Body {
            get {
                return ResourceManager.GetString("Reports_TransactionsDeliveryReport_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التسليم.
        /// </summary>
        internal static string Reports_TransactionsDeliveryReport_Title {
            get {
                return ResourceManager.GetString("Reports_TransactionsDeliveryReport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;للبحث عن المعاملات، قم بالتالي:&lt;/p&gt;
        ///&lt;ol class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;خيارات البحث&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بعرض قسم جديد يحتوي على محددات البحث على النحو التالي:&lt;/span&gt;
        ///		&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///			&lt;li&gt;&lt;span&gt;رقم المعاملة.&lt;/span&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;span&gt;محالة من.&lt;/span&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;span&gt;تاريخ الإحالة.&lt;/span&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;span&gt;درجة الأهمية.&lt;/span&gt;&lt;/li&gt;
        ///			&lt;li&gt;&lt;span&gt;درجة السرية.&lt;/span&gt;&lt;/li&gt;
        ///		&lt;/ul&gt;
        ///	&lt;/li&gt;
        ///&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///	&lt;li&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Search_Index_Body {
            get {
                return ResourceManager.GetString("Search_Index_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث عن المعاملات.
        /// </summary>
        internal static string Search_Index_Title {
            get {
                return ResourceManager.GetString("Search_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تمكن هذه خاصية المستخدم من عرض لوحة قياس مستوى الأداء الإدارة أو الموظف وذلك لإعطاء فكرة عامة عن مستوى أداء وعن عدد المعاملات الموجودة.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-137&quot; class=&quot;sub_title&quot;&gt;عرض لوحة قياس الأداء&lt;/h2&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على تبويب &quot;لوحة قياس الأداء&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم لشاشة لوحة قياس الأداء.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;وسيقوم النظام بعرض البطاقات بناءا على صلاحيات المستخدم.&lt;/span&gt;&lt;/li&gt;
        ///&lt;/ol&gt;
        ///
        ///&lt;h2 id=&quot;calibre_link-138&quot; class=&quot;sub_title&quot;&gt;عر [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shared_DashboardHome_Body {
            get {
                return ResourceManager.GetString("Shared_DashboardHome_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة القياس مستوى الأداء.
        /// </summary>
        internal static string Shared_DashboardHome_Title {
            get {
                return ResourceManager.GetString("Shared_DashboardHome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تمكن هذه خاصية المستخدم من إرسال مشكلة أو استفسار لفريق الدعم.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-133&quot; class=&quot;sub_title&quot;&gt;إرسال مشكلة أو استفسار&lt;/h2&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;الدعم&quot; الموجود في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم لشاشة الدعم.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;إدخال البيانات التالية:&lt;/span&gt;
        ///		&lt;ul class=&quot;list_ block_text&quot;&gt;
        ///		&lt;li&gt;&lt;span&gt;أدخل الموضوع.&lt;/span&gt;&lt;/li&gt;
        ///		&lt;li&gt;&lt;span&gt;أدخل الوصف.&lt;/span&gt;&lt;/li&gt;
        ///		&lt;li&gt;&lt;span&gt;اختر نوع الدعم.&lt;/span&gt;&lt;/li&gt;
        ///		&lt;li&gt;&lt;span&gt;اخت [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shared_Support_Body {
            get {
                return ResourceManager.GetString("Shared_Support_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدعم.
        /// </summary>
        internal static string Shared_Support_Title {
            get {
                return ResourceManager.GetString("Shared_Support_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;تحتوي هذه الجزئية على خاصية تعريف بيانات ورقة الإحالة للمستخدم الذي يمتلك تلك الصلاحية، بحيث يتم من خلالها تعريف ورقة الإحالة التي ستظهر للمستخدم عند إحالة المعاملات عن طريق ورقة الإحالة.&lt;/p&gt;
        ///
        ///&lt;h2 id=&quot;calibre_link-110&quot; class=&quot;sub_title&quot;&gt;إضافة إدارة أو موظف&lt;/h2&gt;
        ///
        ///&lt;p&gt;لإضافة إدارة أو موظف يجب على المستخدم القيام بالخطوات التالية:&lt;/p&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;اسم المستخدم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار قائمة إعدادات المستخدم.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختر &quot;تعريف ورقة [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPreferences_AssignmentPaperSettings_Body {
            get {
                return ResourceManager.GetString("UserPreferences_AssignmentPaperSettings_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف ورقة الإحالة.
        /// </summary>
        internal static string UserPreferences_AssignmentPaperSettings_Title {
            get {
                return ResourceManager.GetString("UserPreferences_AssignmentPaperSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;تحتوي هذه الجزئية على خاصية تعريف قائمة التوزيع للمستخدم الذي يمتلك تلك الصلاحية، بحيث يتمكن المستخدم من تعريف الإدارات والموظفين التي سيتم إرسال نسخ إلكترونية إليهم عند إحالة المعاملة.&lt;/p&gt;
        ///
        ///&lt;h2 id=&quot;calibre_link-113&quot; class=&quot;sub_title&quot;&gt;عرض قوائم التوزيع المعرفة&lt;/h2&gt;
        ///
        ///&lt;p&gt;لإضافة قائمة توزيع يجب على المستخدم القيام بالخطوات التالية:&lt;/p&gt;
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;اسم المستخدم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار قائمة إعدادات المستخدم.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختر &quot;تعريف قائم [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPreferences_DistributionList_Body {
            get {
                return ResourceManager.GetString("UserPreferences_DistributionList_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف قائمة التوزيع.
        /// </summary>
        internal static string UserPreferences_DistributionList_Title {
            get {
                return ResourceManager.GetString("UserPreferences_DistributionList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;تحتوي هذه الجزئية على خاصية التعريف بالتوقيع والتأشير الإلكتروني للمستخدم الذي يمتلك تلك الصلاحية.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-107&quot; class=&quot;sub_title&quot;&gt;تعريف التوقيع أو التأشير&lt;/h2&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;اسم المستخدم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار قائمة إعدادات المستخدم. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختر &quot; التوقيع والتأشير&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;يقوم النظام بنقل المستخدم لشاشة التوقيع والتأشير.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;استخدم أحد الطرق التالي ذكرها لتعريف التوقيع أو ال [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPreferences_Index_Body {
            get {
                return ResourceManager.GetString("UserPreferences_Index_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيع والتأشير.
        /// </summary>
        internal static string UserPreferences_Index_Title {
            get {
                return ResourceManager.GetString("UserPreferences_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;block_text&quot;&gt;تحتوي هذه الجزئية على خاصية تعريف مسار سير محدد لإحالة معاملة من نوع صادر خارجي (مسودة خطاب) وذلك لتقييد عملية الإحالة وفق المسار المعرف.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-128&quot; class=&quot;sub_title&quot;&gt;عرض المسارات المعرفة&lt;/h2&gt;
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;اسم المستخدم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار قائمة إعدادات المستخدم.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختر &quot;تعريف المسارات&quot;.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بنقل المستخدم لشاشة تعريف المسارات.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;وسي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPreferences_TransactionPath_Body {
            get {
                return ResourceManager.GetString("UserPreferences_TransactionPath_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف المسارات.
        /// </summary>
        internal static string UserPreferences_TransactionPath_Title {
            get {
                return ResourceManager.GetString("UserPreferences_TransactionPath_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;تحتوي هذه الجزئية على خاصية تفويض موظف بديل للمستخدم الذي يمتلك تلك الصلاحية، بحيث يتم من خلالها تفويض موظف للعمل على معاملات وضمن صلاحيات موظف آخر لإنجاز عمله خلال فترة زمنية محددة وذلك لعدم وجود الموظف في تلك الفترة المحددة لأي سبب كان.&lt;/p&gt;
        ///&lt;h2 id=&quot;calibre_link-118&quot; class=&quot;sub_title&quot;&gt;عرض تفويضات&lt;/h2&gt;
        ///
        ///&lt;ol&gt;
        ///	&lt;li&gt;&lt;span&gt;الضغط على زر &quot;اسم المستخدم&quot; في أعلى الشاشة.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;سيقوم النظام بإظهار قائمة إعدادات المستخدم.&lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt;اختر &quot;تفويضات الموظف&quot;. &lt;/span&gt;&lt;/li&gt;
        ///	&lt;li&gt;&lt;span&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserPreferences_UserDelegations_Body {
            get {
                return ResourceManager.GetString("UserPreferences_UserDelegations_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفويضات الموظف.
        /// </summary>
        internal static string UserPreferences_UserDelegations_Title {
            get {
                return ResourceManager.GetString("UserPreferences_UserDelegations_Title", resourceCulture);
            }
        }
    }
}
