#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MCS.DoconutMVC.Helpers;
    using DoconutViewer;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/doconut/_Layout.cshtml")]
    public partial class _Views_Shared_doconut__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_doconut__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"vi" +
"ewport\" content=\"user-scalable=no, width=device-width, initial-scale=1, maximum-" +
"scale=1\" />\r\n    <title>");


            
            #line 6 "..\..\Views\Shared\doconut\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@" wedrfef </title>
    <script>
        /*
         * TO-DO: Consider removing Approved_StampUri and all of its references
        */
        //var Approved_StampUri = 'Html.GetWebResourceUrl(""MCS.DoconutMVC.images.Approved_Stamp.png"")';
        var basePath = '");


            
            #line 12 "..\..\Views\Shared\doconut\_Layout.cshtml"
                   Write(Session["BasePath"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    ");



WriteLiteral("\r\n    ");


            
            #line 15 "..\..\Views\Shared\doconut\_Layout.cshtml"
Write(RenderSection("css", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");



WriteLiteral("\r\n\r\n    <link href=\"");


            
            #line 18 "..\..\Views\Shared\doconut\_Layout.cshtml"
           Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.Annotations.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" />\r\n    <!-- jQuery-->\r\n    <script src=\"");


            
            #line 20 "..\..\Views\Shared\doconut\_Layout.cshtml"
            Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.jquery-3.6.4.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <meta name=\"description\" content=\"Asp.net" +
" mvc document viewer free sample code in C# and vb.net. View office documents an" +
"d pdf files online in asp.net\" />\r\n\r\n</head>\r\n<body>\r\n    ");


            
            #line 25 "..\..\Views\Shared\doconut\_Layout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 26 "..\..\Views\Shared\doconut\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
