//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.DocRepository.Provider.ECM.ECMService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckInNewRequestData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CheckInNewRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachmentContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCS.DocRepository.Provider.ECM.ECMService.DocumentType DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_DestinationEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_SourceEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MOR_TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionDateHijriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionId1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AttachmentContent {
            get {
                return this.AttachmentContentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentContentField, value) != true)) {
                    this.AttachmentContentField = value;
                    this.RaisePropertyChanged("AttachmentContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIDField, value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIDField, value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTitle {
            get {
                return this.DocumentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTitleField, value) != true)) {
                    this.DocumentTitleField = value;
                    this.RaisePropertyChanged("DocumentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MCS.DocRepository.Provider.ECM.ECMService.DocumentType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_DestinationEntity {
            get {
                return this.MOR_DestinationEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_DestinationEntityField, value) != true)) {
                    this.MOR_DestinationEntityField = value;
                    this.RaisePropertyChanged("MOR_DestinationEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_SourceEntity {
            get {
                return this.MOR_SourceEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_SourceEntityField, value) != true)) {
                    this.MOR_SourceEntityField = value;
                    this.RaisePropertyChanged("MOR_SourceEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MOR_TransactionDate {
            get {
                return this.MOR_TransactionDateField;
            }
            set {
                if ((this.MOR_TransactionDateField.Equals(value) != true)) {
                    this.MOR_TransactionDateField = value;
                    this.RaisePropertyChanged("MOR_TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_TransactionDateHijri {
            get {
                return this.MOR_TransactionDateHijriField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionDateHijriField, value) != true)) {
                    this.MOR_TransactionDateHijriField = value;
                    this.RaisePropertyChanged("MOR_TransactionDateHijri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_TransactionID {
            get {
                return this.MOR_TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionIDField, value) != true)) {
                    this.MOR_TransactionIDField = value;
                    this.RaisePropertyChanged("MOR_TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="MOR_TransactionId")]
        public string MOR_TransactionId1 {
            get {
                return this.MOR_TransactionId1Field;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionId1Field, value) != true)) {
                    this.MOR_TransactionId1Field = value;
                    this.RaisePropertyChanged("MOR_TransactionId1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_UserID {
            get {
                return this.MOR_UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_UserIDField, value) != true)) {
                    this.MOR_UserIDField = value;
                    this.RaisePropertyChanged("MOR_UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileIDField, value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentType", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    public enum DocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Application = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Binary = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DigitalMedia = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OFFSITEREQUEST = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RetentionCategory = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckInNewResponseData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CheckInNewResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileRequestData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetFileRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileResponseData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class GetFileResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachmentContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCheckedOutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_DestinationEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_SourceEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MOR_TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevisionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WCC_CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WCC_LastModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WCC_ReleaseDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AttachmentContent {
            get {
                return this.AttachmentContentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentContentField, value) != true)) {
                    this.AttachmentContentField = value;
                    this.RaisePropertyChanged("AttachmentContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentSize {
            get {
                return this.AttachmentSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentSizeField, value) != true)) {
                    this.AttachmentSizeField = value;
                    this.RaisePropertyChanged("AttachmentSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIDField, value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTitle {
            get {
                return this.DocumentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTitleField, value) != true)) {
                    this.DocumentTitleField = value;
                    this.RaisePropertyChanged("DocumentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCheckedOut {
            get {
                return this.IsCheckedOutField;
            }
            set {
                if ((this.IsCheckedOutField.Equals(value) != true)) {
                    this.IsCheckedOutField = value;
                    this.RaisePropertyChanged("IsCheckedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_DestinationEntity {
            get {
                return this.MOR_DestinationEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_DestinationEntityField, value) != true)) {
                    this.MOR_DestinationEntityField = value;
                    this.RaisePropertyChanged("MOR_DestinationEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_SourceEntity {
            get {
                return this.MOR_SourceEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_SourceEntityField, value) != true)) {
                    this.MOR_SourceEntityField = value;
                    this.RaisePropertyChanged("MOR_SourceEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MOR_TransactionDate {
            get {
                return this.MOR_TransactionDateField;
            }
            set {
                if ((this.MOR_TransactionDateField.Equals(value) != true)) {
                    this.MOR_TransactionDateField = value;
                    this.RaisePropertyChanged("MOR_TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_TransactionID {
            get {
                return this.MOR_TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionIDField, value) != true)) {
                    this.MOR_TransactionIDField = value;
                    this.RaisePropertyChanged("MOR_TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_UserID {
            get {
                return this.MOR_UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_UserIDField, value) != true)) {
                    this.MOR_UserIDField = value;
                    this.RaisePropertyChanged("MOR_UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevisionID {
            get {
                return this.RevisionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RevisionIDField, value) != true)) {
                    this.RevisionIDField = value;
                    this.RaisePropertyChanged("RevisionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WCC_CreateDate {
            get {
                return this.WCC_CreateDateField;
            }
            set {
                if ((this.WCC_CreateDateField.Equals(value) != true)) {
                    this.WCC_CreateDateField = value;
                    this.RaisePropertyChanged("WCC_CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WCC_LastModifiedDate {
            get {
                return this.WCC_LastModifiedDateField;
            }
            set {
                if ((this.WCC_LastModifiedDateField.Equals(value) != true)) {
                    this.WCC_LastModifiedDateField = value;
                    this.RaisePropertyChanged("WCC_LastModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WCC_ReleaseDate {
            get {
                return this.WCC_ReleaseDateField;
            }
            set {
                if ((this.WCC_ReleaseDateField.Equals(value) != true)) {
                    this.WCC_ReleaseDateField = value;
                    this.RaisePropertyChanged("WCC_ReleaseDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckInUniversalRequestData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CheckInUniversalRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AttachmentContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCS.DocRepository.Provider.ECM.ECMService.DocumentType DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_DestinationEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_SourceEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MOR_TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionDateHijriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOR_UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] AttachmentContent {
            get {
                return this.AttachmentContentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentContentField, value) != true)) {
                    this.AttachmentContentField = value;
                    this.RaisePropertyChanged("AttachmentContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIDField, value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIDField, value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName {
            get {
                return this.DocumentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNameField, value) != true)) {
                    this.DocumentNameField = value;
                    this.RaisePropertyChanged("DocumentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentTitle {
            get {
                return this.DocumentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTitleField, value) != true)) {
                    this.DocumentTitleField = value;
                    this.RaisePropertyChanged("DocumentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MCS.DocRepository.Provider.ECM.ECMService.DocumentType DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((this.DocumentTypeField.Equals(value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_DestinationEntity {
            get {
                return this.MOR_DestinationEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_DestinationEntityField, value) != true)) {
                    this.MOR_DestinationEntityField = value;
                    this.RaisePropertyChanged("MOR_DestinationEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_SourceEntity {
            get {
                return this.MOR_SourceEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_SourceEntityField, value) != true)) {
                    this.MOR_SourceEntityField = value;
                    this.RaisePropertyChanged("MOR_SourceEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MOR_TransactionDate {
            get {
                return this.MOR_TransactionDateField;
            }
            set {
                if ((this.MOR_TransactionDateField.Equals(value) != true)) {
                    this.MOR_TransactionDateField = value;
                    this.RaisePropertyChanged("MOR_TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_TransactionDateHijri {
            get {
                return this.MOR_TransactionDateHijriField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionDateHijriField, value) != true)) {
                    this.MOR_TransactionDateHijriField = value;
                    this.RaisePropertyChanged("MOR_TransactionDateHijri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_TransactionID {
            get {
                return this.MOR_TransactionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_TransactionIDField, value) != true)) {
                    this.MOR_TransactionIDField = value;
                    this.RaisePropertyChanged("MOR_TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOR_UserID {
            get {
                return this.MOR_UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MOR_UserIDField, value) != true)) {
                    this.MOR_UserIDField = value;
                    this.RaisePropertyChanged("MOR_UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileIDField, value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckInUniversalResponseData", Namespace="http://schemas.datacontract.org/2004/07/YESSER.NCS.ECM.IntegrationService.Contrac" +
        "ts.DataContracts")]
    [System.SerializableAttribute()]
    public partial class CheckInUniversalResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader HeaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocID {
            get {
                return this.DocIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DocIDField, value) != true)) {
                    this.DocIDField = value;
                    this.RaisePropertyChanged("DocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MCS.DocRepository.Provider.ECM.ECMService.ResponseHeader Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ECMService.IECMService")]
    public interface IECMService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/Insert", ReplyAction="http://tempuri.org/IECMService/InsertResponse")]
        MCS.DocRepository.Provider.ECM.ECMService.CheckInNewResponseData Insert(MCS.DocRepository.Provider.ECM.ECMService.CheckInNewRequestData Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/Insert", ReplyAction="http://tempuri.org/IECMService/InsertResponse")]
        System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.CheckInNewResponseData> InsertAsync(MCS.DocRepository.Provider.ECM.ECMService.CheckInNewRequestData Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/GetFile", ReplyAction="http://tempuri.org/IECMService/GetFileResponse")]
        MCS.DocRepository.Provider.ECM.ECMService.GetFileResponseData GetFile(MCS.DocRepository.Provider.ECM.ECMService.GetFileRequestData Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/GetFile", ReplyAction="http://tempuri.org/IECMService/GetFileResponse")]
        System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.GetFileResponseData> GetFileAsync(MCS.DocRepository.Provider.ECM.ECMService.GetFileRequestData Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/Update", ReplyAction="http://tempuri.org/IECMService/UpdateResponse")]
        MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalResponseData Update(MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalRequestData Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IECMService/Update", ReplyAction="http://tempuri.org/IECMService/UpdateResponse")]
        System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalResponseData> UpdateAsync(MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalRequestData Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IECMServiceChannel : MCS.DocRepository.Provider.ECM.ECMService.IECMService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ECMServiceClient : System.ServiceModel.ClientBase<MCS.DocRepository.Provider.ECM.ECMService.IECMService>, MCS.DocRepository.Provider.ECM.ECMService.IECMService {
        
        public ECMServiceClient() {
        }
        
        public ECMServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ECMServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECMServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ECMServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MCS.DocRepository.Provider.ECM.ECMService.CheckInNewResponseData Insert(MCS.DocRepository.Provider.ECM.ECMService.CheckInNewRequestData Request) {
            return base.Channel.Insert(Request);
        }
        
        public System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.CheckInNewResponseData> InsertAsync(MCS.DocRepository.Provider.ECM.ECMService.CheckInNewRequestData Request) {
            return base.Channel.InsertAsync(Request);
        }
        
        public MCS.DocRepository.Provider.ECM.ECMService.GetFileResponseData GetFile(MCS.DocRepository.Provider.ECM.ECMService.GetFileRequestData Request) {
            return base.Channel.GetFile(Request);
        }
        
        public System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.GetFileResponseData> GetFileAsync(MCS.DocRepository.Provider.ECM.ECMService.GetFileRequestData Request) {
            return base.Channel.GetFileAsync(Request);
        }
        
        public MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalResponseData Update(MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalRequestData Request) {
            return base.Channel.Update(Request);
        }
        
        public System.Threading.Tasks.Task<MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalResponseData> UpdateAsync(MCS.DocRepository.Provider.ECM.ECMService.CheckInUniversalRequestData Request) {
            return base.Channel.UpdateAsync(Request);
        }
    }
}
