//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceView", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخزين بعد الصفحة.
        /// </summary>
        internal static string AfterPage {
            get {
                return ResourceManager.GetString("AfterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهم.
        /// </summary>
        internal static string ArrowToolTip {
            get {
                return ResourceManager.GetString("ArrowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباركود.
        /// </summary>
        internal static string BarcodeToolTip {
            get {
                return ResourceManager.GetString("BarcodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دائرة.
        /// </summary>
        internal static string CircleToolTip {
            get {
                return ResourceManager.GetString("CircleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف كل الإضافات.
        /// </summary>
        internal static string ClearAnnotationsToolTip {
            get {
                return ResourceManager.GetString("ClearAnnotationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر هنا .
        /// </summary>
        internal static string ClickOrDragToUpload {
            get {
                return ResourceManager.GetString("ClickOrDragToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الأرشفة.
        /// </summary>
        internal static string DeleteDocumentToolTip {
            get {
                return ResourceManager.GetString("DeleteDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الصفحة.
        /// </summary>
        internal static string DeletePageToolTip {
            get {
                return ResourceManager.GetString("DeletePageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string DownloadDocumentToolTip {
            get {
                return ResourceManager.GetString("DownloadDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string EditToolTip {
            get {
                return ResourceManager.GetString("EditToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Exitbtn {
            get {
                return ResourceManager.GetString("Exitbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتابة الحرة.
        /// </summary>
        internal static string FreehandToolTip {
            get {
                return ResourceManager.GetString("FreehandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط.
        /// </summary>
        internal static string lineToolTip {
            get {
                return ResourceManager.GetString("lineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخزين قبل الصفحة.
        /// </summary>
        internal static string PrePage {
            get {
                return ResourceManager.GetString("PrePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعه.
        /// </summary>
        internal static string PrintDocumentToolTip {
            get {
                return ResourceManager.GetString("PrintDocumentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستطيل.
        /// </summary>
        internal static string RectangleToolTip {
            get {
                return ResourceManager.GetString("RectangleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح ضوئي عادي.
        /// </summary>
        internal static string RegulerArchiving {
            get {
                return ResourceManager.GetString("RegulerArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير الصفحة.
        /// </summary>
        internal static string ReplacePage {
            get {
                return ResourceManager.GetString("ReplacePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الماسح الضوئي.
        /// </summary>
        internal static string ScannerToolTip {
            get {
                return ResourceManager.GetString("ScannerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الماسح الضوئي مع الالوان.
        /// </summary>
        internal static string ScannerWithColorsToolTip {
            get {
                return ResourceManager.GetString("ScannerWithColorsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع.
        /// </summary>
        internal static string SignatureToolTip {
            get {
                return ResourceManager.GetString("SignatureToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التأشير.
        /// </summary>
        internal static string StampToolTip {
            get {
                return ResourceManager.GetString("StampToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاول.
        /// </summary>
        internal static string TheFirst {
            get {
                return ResourceManager.GetString("TheFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاخير.
        /// </summary>
        internal static string TheLast {
            get {
                return ResourceManager.GetString("TheLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string TheNext {
            get {
                return ResourceManager.GetString("TheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string ThePrevious {
            get {
                return ResourceManager.GetString("ThePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثلث.
        /// </summary>
        internal static string TriangleToolTip {
            get {
                return ResourceManager.GetString("TriangleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل الملف.
        /// </summary>
        internal static string UploadDocument {
            get {
                return ResourceManager.GetString("UploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string UploadFileToolTip {
            get {
                return ResourceManager.GetString("UploadFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تكبير.
        /// </summary>
        internal static string ZoomInToolTip {
            get {
                return ResourceManager.GetString("ZoomInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصغير.
        /// </summary>
        internal static string ZoomOutToolTip {
            get {
                return ResourceManager.GetString("ZoomOutToolTip", resourceCulture);
            }
        }
    }
}
