//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.StatusCode", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الاجراء مستخدم في النظام, لا يمكن حذفه.
        /// </summary>
        internal static string ActionIsUsed {
            get {
                return ResourceManager.GetString("ActionIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد إجراء من نوع للإطلاع لهذه الإدارة.
        /// </summary>
        internal static string ActionSendCopyToViewNotFound {
            get {
                return ResourceManager.GetString("ActionSendCopyToViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد إجراء من نوع إرسال معاملة الأصل لهذه الإدارة, يرجى مراجعة مدير النظام.
        /// </summary>
        internal static string ActionSendMainTransactionNotFound {
            get {
                return ResourceManager.GetString("ActionSendMainTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة المراد نقلها هي أحد ابناء الإدارة المنقول اليها  .
        /// </summary>
        internal static string AlreadyChildOfThisEntity {
            get {
                return ResourceManager.GetString("AlreadyChildOfThisEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة التعميم غير موجودة.
        /// </summary>
        internal static string AssignmentGroupNotFound {
            get {
                return ResourceManager.GetString("AssignmentGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إحالة المعاملة.
        /// </summary>
        internal static string AssignmentsAssign {
            get {
                return ResourceManager.GetString("AssignmentsAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إسترجاع المعاملة.
        /// </summary>
        internal static string AssignmentsWithdrawTransaction {
            get {
                return ResourceManager.GetString("AssignmentsWithdrawTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد لديك مهام غير منتهية لذلك لا يمكنك  اتمام عملية الاحالة.
        /// </summary>
        internal static string AssignmentTasksNotCompleted {
            get {
                return ResourceManager.GetString("AssignmentTasksNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تصميم لرمز التشفير, يرجى مراجعة مدير النظام.
        /// </summary>
        internal static string BarcodeDesignNotFound {
            get {
                return ResourceManager.GetString("BarcodeDesignNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصميم رمز التشفير غير متوفر.
        /// </summary>
        internal static string BarcodeNotAvailable {
            get {
                return ResourceManager.GetString("BarcodeNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إلغاء تفعيل هذا الدور وذلك لأنه مستخدم من قبل أحد المستخدمين.
        /// </summary>
        internal static string CanNotDeactivateRoleThereAreUsersUseThisRole {
            get {
                return ResourceManager.GetString("CanNotDeactivateRoleThereAreUsersUseThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن تكون الإدارة الرئيسية هي نفسها الإدارة المندمجة.
        /// </summary>
        internal static string CanNotMergeEntityToItself {
            get {
                return ResourceManager.GetString("CanNotMergeEntityToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن دمج الإدارات المرتبطة بنظام خارجي.
        /// </summary>
        internal static string CanNotMergeExternalEntity {
            get {
                return ResourceManager.GetString("CanNotMergeExternalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن دمج الإدارة بإدارة فرعية تابعة لها.
        /// </summary>
        internal static string CanNotMergeParentEntityToChildEntity {
            get {
                return ResourceManager.GetString("CanNotMergeParentEntityToChildEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن نقل الإدارة إلى نفسها.
        /// </summary>
        internal static string CanNotMoveEntityToItself {
            get {
                return ResourceManager.GetString("CanNotMoveEntityToItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن نقل الإدارات المرتبطة بظام خارجي.
        /// </summary>
        internal static string CanNotMoveExternalEntity {
            get {
                return ResourceManager.GetString("CanNotMoveExternalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن نقل الإدارة لإدارة فرعية تابعة لها.
        /// </summary>
        internal static string CanNotMoveParentEntityToChildEntity {
            get {
                return ResourceManager.GetString("CanNotMoveParentEntityToChildEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إعادة المعاملة لنفس المستخدم.
        /// </summary>
        internal static string CantReturnToSelf {
            get {
                return ResourceManager.GetString("CantReturnToSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل البيانات الأساسية للمعاملة.
        /// </summary>
        internal static string ConnotUpdateTransactionBasicInfo {
            get {
                return ResourceManager.GetString("ConnotUpdateTransactionBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن إضافة نوع معاملة موجود مسبقا.
        /// </summary>
        internal static string CounterExisted {
            get {
                return ResourceManager.GetString("CounterExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف عداد مستخدم في المعاملات.
        /// </summary>
        internal static string DeleteCounterDetail {
            get {
                return ResourceManager.GetString("DeleteCounterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف هذه الصلاحية غير مسموح.
        /// </summary>
        internal static string DeletePermissionNotAllow {
            get {
                return ResourceManager.GetString("DeletePermissionNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة الواردة مدخل مسبقا في النظام، الرجاء إدخال رقم معاملة واردة لم يتم إدخاله مسبقا.
        /// </summary>
        internal static string DocumentNumberAlreadyExist {
            get {
                return ResourceManager.GetString("DocumentNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة إجباري.
        /// </summary>
        internal static string DocumentNumberRequired {
            get {
                return ResourceManager.GetString("DocumentNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إدخال معاملتين مسودة خطاب لها نفس الوصف لجهة واحدة في اليوم نفسه، يرجى تغيير الوصف أو جهة الصادر.
        /// </summary>
        internal static string DraftAlreadyExist {
            get {
                return ResourceManager.GetString("DraftAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشروع الصادر غير مخول.
        /// </summary>
        internal static string DraftOutboundNotAuthorized {
            get {
                return ResourceManager.GetString("DraftOutboundNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن اضافة تفويض مكرر.
        /// </summary>
        internal static string DuplicateUserDeligation {
            get {
                return ResourceManager.GetString("DuplicateUserDeligation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال مستوى السرية.
        /// </summary>
        internal static string ExplanationConfidentialityRequired {
            get {
                return ResourceManager.GetString("ExplanationConfidentialityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فني في النظام, الرجاء مراجعة مدير النظام.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم غير فعال ، يرجى مراجعة مدير النظام لتفعيله.
        /// </summary>
        internal static string InActiveUser {
            get {
                return ResourceManager.GetString("InActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإجراء للإحالات.
        /// </summary>
        internal static string InvalidActionType {
            get {
                return ResourceManager.GetString("InvalidActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ المدخل غير صحيح , يجب أن يكون أكبر من تاريخ نهاية المهمة.
        /// </summary>
        internal static string InvalidExtendTaskDate {
            get {
                return ResourceManager.GetString("InvalidExtendTaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الدخول القديم غير صحيح.
        /// </summary>
        internal static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة خاطئة.
        /// </summary>
        internal static string InvalidOrgUnit {
            get {
                return ResourceManager.GetString("InvalidOrgUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المهمة الأب غير صحيح.
        /// </summary>
        internal static string InvalidParentTask {
            get {
                return ResourceManager.GetString("InvalidParentTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تتكون كلمة السر من  6 احرف على الاقل.
        /// </summary>
        internal static string InvalidPasswordRequiredLength {
            get {
                return ResourceManager.GetString("InvalidPasswordRequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمة خاطئة.
        /// </summary>
        internal static string InvalidTask {
            get {
                return ResourceManager.GetString("InvalidTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سير عمل المهمة خطأ.
        /// </summary>
        internal static string InvalidTaskWorkflow {
            get {
                return ResourceManager.GetString("InvalidTaskWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم خطأ.
        /// </summary>
        internal static string InvalidUserTask {
            get {
                return ResourceManager.GetString("InvalidUserTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تجزئة المهمة لأكثر من مستوى.
        /// </summary>
        internal static string LimitaionSubTask {
            get {
                return ResourceManager.GetString("LimitaionSubTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إغلاق هذا الحساب ، يرجى إعادة المحاولة لاحقًا..
        /// </summary>
        internal static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد استنفذت الحد المسموح به من الادارات.
        /// </summary>
        internal static string MaxOrgunitsReached {
            get {
                return ResourceManager.GetString("MaxOrgunitsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد استنفذت الحد المسموح به من المستخدمين.
        /// </summary>
        internal static string MaxUsersReached {
            get {
                return ResourceManager.GetString("MaxUsersReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المرسلة غير صحيحة.
        /// </summary>
        internal static string ModelNotValid {
            get {
                return ResourceManager.GetString("ModelNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملاتي غير مخولة.
        /// </summary>
        internal static string MyTransactionNotAuthorized {
            get {
                return ResourceManager.GetString("MyTransactionNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون عداد للوحدة.
        /// </summary>
        internal static string NoCounter {
            get {
                return ResourceManager.GetString("NoCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد معاملات توافق المدخلات.
        /// </summary>
        internal static string NoDeliveryReportFound {
            get {
                return ResourceManager.GetString("NoDeliveryReportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد اداره رئيسيه.
        /// </summary>
        internal static string NoOrgUnitRootDefiened {
            get {
                return ResourceManager.GetString("NoOrgUnitRootDefiened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت العملية بنجاح.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين التالية أسمائهم موجودون في كلتا الإدارتين.
        /// </summary>
        internal static string OneOfTheUsersIsMemberOfTwoEntities {
            get {
                return ResourceManager.GetString("OneOfTheUsersIsMemberOfTwoEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن دمج هذه الإدارة لوجود معاملات في صندوق المعاملات والنسخ المستلمة من جهات خارجية.
        /// </summary>
        internal static string OrgUnitHasTransactionsFromExternalParties {
            get {
                return ResourceManager.GetString("OrgUnitHasTransactionsFromExternalParties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة غير مخولة.
        /// </summary>
        internal static string OrgunitNotAuthorized {
            get {
                return ResourceManager.GetString("OrgunitNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الإدارة.
        /// </summary>
        internal static string OrgUnitRequired {
            get {
                return ResourceManager.GetString("OrgUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد تشابه بين إسم الإدارة المراد نقلها و الإدارة المنقول اليها أو أحد أبناء الإدارة المنقول إليها ، يرجى العمل على تغيير الأسماء التالية.
        /// </summary>
        internal static string OrgUnitsHaveSameName {
            get {
                return ResourceManager.GetString("OrgUnitsHaveSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارتين المندمجتين تحتويان على إدارات فرعية أسمائها متشابهة، يرجى العمل على تغيير الأسماء التالية.
        /// </summary>
        internal static string OrgUnitsToBeMergedHaveSameName {
            get {
                return ResourceManager.GetString("OrgUnitsToBeMergedHaveSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، رمز التحقق غير صالح. يرجى المحاولة مرة أخرى..
        /// </summary>
        internal static string OTPInvalid {
            get {
                return ResourceManager.GetString("OTPInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا ، رمز التحقق قديم جدا. يرجى الحصول على واحد جديد.
        /// </summary>
        internal static string OTPVeryOld {
            get {
                return ResourceManager.GetString("OTPVeryOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة السر غير صحيحة .
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تتكون كلمة السر من ارقام فقط.
        /// </summary>
        internal static string PasswordRequireDigit {
            get {
                return ResourceManager.GetString("PasswordRequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تتكون كلمة السر من احرف صغيرة .
        /// </summary>
        internal static string PasswordRequireLowercase {
            get {
                return ResourceManager.GetString("PasswordRequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تتكون كلمة السر من حروف و ارقام .
        /// </summary>
        internal static string PasswordRequireNonLetterOrDigit {
            get {
                return ResourceManager.GetString("PasswordRequireNonLetterOrDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تتكون كلمة السر من احرف كبيرة .
        /// </summary>
        internal static string PasswordRequireUppercase {
            get {
                return ResourceManager.GetString("PasswordRequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن سحب المعاملة لعدم امتلاك المستخدم الصلاحية الخاصة بسحب المعاملات.
        /// </summary>
        internal static string PermissionAssignmentsWithdrawTransaction {
            get {
                return ResourceManager.GetString("PermissionAssignmentsWithdrawTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك صلاحية لتخصيص المعاملات من هذه السلة.
        /// </summary>
        internal static string PermissionAssignTo {
            get {
                return ResourceManager.GetString("PermissionAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إحالة المعاملة لعدم امتلاك صلاحية إحالة المعاملة إلى إدارة أخرى.
        /// </summary>
        internal static string PermissionAssignToEmployeeInOtherDepartment {
            get {
                return ResourceManager.GetString("PermissionAssignToEmployeeInOtherDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إحالة المعاملة لعدم امتلاك صلاحية إحالة المعاملة إلى إدارة أخرى.
        /// </summary>
        internal static string PermissionAssignToOtherDepartment {
            get {
                return ResourceManager.GetString("PermissionAssignToOtherDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إنشاء وارد.
        /// </summary>
        internal static string PermissionCreateInbound {
            get {
                return ResourceManager.GetString("PermissionCreateInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الوارد.
        /// </summary>
        internal static string PermissionEditInbound {
            get {
                return ResourceManager.GetString("PermissionEditInbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إستعراض المحرر.
        /// </summary>
        internal static string PermissionEditor {
            get {
                return ResourceManager.GetString("PermissionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إستعراض الإحالات.
        /// </summary>
        internal static string PermissionEditorAssignments {
            get {
                return ResourceManager.GetString("PermissionEditorAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إستعراض مشروع الصادر.
        /// </summary>
        internal static string PermissionEditorDraft {
            get {
                return ResourceManager.GetString("PermissionEditorDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إستعراض الشروحات.
        /// </summary>
        internal static string PermissionEditorExplanations {
            get {
                return ResourceManager.GetString("PermissionEditorExplanations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إستعراض المعاملات.
        /// </summary>
        internal static string PermissionEditorViewTransactions {
            get {
                return ResourceManager.GetString("PermissionEditorViewTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة مرفقات.
        /// </summary>
        internal static string PermissionInboundAddAttachments {
            get {
                return ResourceManager.GetString("PermissionInboundAddAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة أسماء.
        /// </summary>
        internal static string PermissionInboundAddNames {
            get {
                return ResourceManager.GetString("PermissionInboundAddNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف مرفقات الوارد.
        /// </summary>
        internal static string PermissionInboundDeleteAttachments {
            get {
                return ResourceManager.GetString("PermissionInboundDeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف أسماء الوارد.
        /// </summary>
        internal static string PermissionInboundDeleteNames {
            get {
                return ResourceManager.GetString("PermissionInboundDeleteNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة ربط.
        /// </summary>
        internal static string PermissionLinkAddLink {
            get {
                return ResourceManager.GetString("PermissionLinkAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النوع من الربط مستخدم في النظام, لا يمكن حذفه.
        /// </summary>
        internal static string PermissionLinkDeleteLink {
            get {
                return ResourceManager.GetString("PermissionLinkDeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إنشاء صادر خارجي.
        /// </summary>
        internal static string PermissionOutbound {
            get {
                return ResourceManager.GetString("PermissionOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة مرفقات.
        /// </summary>
        internal static string PermissionOutboundAddAttachments {
            get {
                return ResourceManager.GetString("PermissionOutboundAddAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة صور.
        /// </summary>
        internal static string PermissionOutboundAddCopies {
            get {
                return ResourceManager.GetString("PermissionOutboundAddCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة أسماء.
        /// </summary>
        internal static string PermissionOutboundAddNames {
            get {
                return ResourceManager.GetString("PermissionOutboundAddNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف مرفقات الصادر.
        /// </summary>
        internal static string PermissionOutboundDeleteAttachments {
            get {
                return ResourceManager.GetString("PermissionOutboundDeleteAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف صور الصادر.
        /// </summary>
        internal static string PermissionOutboundDeleteCopies {
            get {
                return ResourceManager.GetString("PermissionOutboundDeleteCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف أسماء الصادر.
        /// </summary>
        internal static string PermissionOutboundDeleteNames {
            get {
                return ResourceManager.GetString("PermissionOutboundDeleteNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل الصادر.
        /// </summary>
        internal static string PermissionOutboundEditOutbound {
            get {
                return ResourceManager.GetString("PermissionOutboundEditOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إنشاء مشروع صادر.
        /// </summary>
        internal static string PermissionOutboundOutboundDraft {
            get {
                return ResourceManager.GetString("PermissionOutboundOutboundDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن طباعة بيان التسليم.
        /// </summary>
        internal static string PermissionPrintDeliveryData {
            get {
                return ResourceManager.GetString("PermissionPrintDeliveryData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف صلاحية مرتبطة بشروحات.
        /// </summary>
        internal static string PermissionRelatedToExplanation {
            get {
                return ResourceManager.GetString("PermissionRelatedToExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف صلاحية مرتبطة بمعاملة.
        /// </summary>
        internal static string PermissionRelatedToTransactions {
            get {
                return ResourceManager.GetString("PermissionRelatedToTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إضافة مهمة.
        /// </summary>
        internal static string PermissionTasksInsertionAddTask {
            get {
                return ResourceManager.GetString("PermissionTasksInsertionAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف مهمة.
        /// </summary>
        internal static string PermissionTasksInsertionDeleteTask {
            get {
                return ResourceManager.GetString("PermissionTasksInsertionDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل تاريخ المهمة.
        /// </summary>
        internal static string PermissionTasksInsertionEditTaskDate {
            get {
                return ResourceManager.GetString("PermissionTasksInsertionEditTaskDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تجزئة المهمة.
        /// </summary>
        internal static string PermissionTasksInsertionSubTasking {
            get {
                return ResourceManager.GetString("PermissionTasksInsertionSubTasking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراسل تم اضافته مسبقآ .
        /// </summary>
        internal static string RepoterExist {
            get {
                return ResourceManager.GetString("RepoterExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ اثناء تنفيذ العملية.
        /// </summary>
        internal static string ResetPasswordOperationFailed {
            get {
                return ResourceManager.GetString("ResetPasswordOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز توثيق البريد الإلكتروني غير صحيح.
        /// </summary>
        internal static string ResetTokenInvalid {
            get {
                return ResourceManager.GetString("ResetTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التوثيق غير صحيح.
        /// </summary>
        internal static string RestCodeInvalid {
            get {
                return ResourceManager.GetString("RestCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن سحب المعاملة لإنها موجودة لديك.
        /// </summary>
        internal static string RevertAssignmentToYou {
            get {
                return ResourceManager.GetString("RevertAssignmentToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مخول لإرسال معاملة.
        /// </summary>
        internal static string SentTransactionsNotAuthorized {
            get {
                return ResourceManager.GetString("SentTransactionsNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواضيع المقترحة مرتبطة بمعاملات.
        /// </summary>
        internal static string SubjectClassificationRelatedToTransactions {
            get {
                return ResourceManager.GetString("SubjectClassificationRelatedToTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن الدخول الى النظام بسبب انتهاء صلاحية النظام.
        /// </summary>
        internal static string SystemExpired {
            get {
                return ResourceManager.GetString("SystemExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المهمة غير موجودة.
        /// </summary>
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العميل غير فعال ,يرجى مراجعة مدير النظام.
        /// </summary>
        internal static string TenantNotActive {
            get {
                return ResourceManager.GetString("TenantNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العميل غير موجود,يرجى مراجعة مدير النظام.
        /// </summary>
        internal static string TenantNotFound {
            get {
                return ResourceManager.GetString("TenantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدور الذي أدخلته مكرر، يرجى إدخال اسم أخر.
        /// </summary>
        internal static string ThisRoleIsAlreadyExist {
            get {
                return ResourceManager.GetString("ThisRoleIsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إدخال معاملتين صادر خارجي لها نفس الوصف لجهة واحدة في اليوم نفسه، يرجى تغيير الوصف أو جهة الصادر.
        /// </summary>
        internal static string TransactionAlreadyExist {
            get {
                return ResourceManager.GetString("TransactionAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحالات المعاملة لا يمكن أن تكون خالية.
        /// </summary>
        internal static string TransactionAssignmentsCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("TransactionAssignmentsCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك الصلاحيه بإضافة أو تعديل معامله مستوى السريه لها سري.
        /// </summary>
        internal static string TransactionConfidentialityRequired {
            get {
                return ResourceManager.GetString("TransactionConfidentialityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن ربط المعامله بنفسها.
        /// </summary>
        internal static string TransactionCycleLinked {
            get {
                return ResourceManager.GetString("TransactionCycleLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم الربط بهذه المعاملة من قبل، لا يمكنك ربط المعاملة مرة أخرى.
        /// </summary>
        internal static string TransactionDoubleLinked {
            get {
                return ResourceManager.GetString("TransactionDoubleLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشروع الصادر منشأ من قبل.
        /// </summary>
        internal static string TransactionDraftAlreadyCreated {
            get {
                return ResourceManager.GetString("TransactionDraftAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المعاملة غير موجودة.
        /// </summary>
        internal static string TransactionNotFound {
            get {
                return ResourceManager.GetString("TransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحد المستخدمين المعرفين بالمسار لا يمتلك الصلاحية المطلوبة.
        /// </summary>
        internal static string TransactionPathConfidentialityRequired {
            get {
                return ResourceManager.GetString("TransactionPathConfidentialityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليس لديك الصلاحيه بإضافة أو تعديل معامله من نوع سري.
        /// </summary>
        internal static string TransactionSourceTypeConfidentialityRequired {
            get {
                return ResourceManager.GetString("TransactionSourceTypeConfidentialityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم طباعة بيان التسليم, لذلك لا يمكنك التعديل على المعامله.
        /// </summary>
        internal static string UpdateNotAllow {
            get {
                return ResourceManager.GetString("UpdateNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل صورة المعاملة.
        /// </summary>
        internal static string UpdateNotAllowDueToActionAsCopy {
            get {
                return ResourceManager.GetString("UpdateNotAllowDueToActionAsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لا يمكن تغير القيم الإبتدائيه لعداد مستخدم في معاملات.
        /// </summary>
        internal static string UsedCounter {
            get {
                return ResourceManager.GetString("UsedCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني المدخل معرف مسبقا.
        /// </summary>
        internal static string UserEmailAlreadyExist {
            get {
                return ResourceManager.GetString("UserEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المجموعة معرف من قبل.
        /// </summary>
        internal static string UserGroupNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserGroupNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم المدخل معرف مسبقا.
        /// </summary>
        internal static string UserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم أو البريد الالكتروني غير صحيح.
        /// </summary>
        internal static string UsernameOrEmailNotCorrect {
            get {
                return ResourceManager.GetString("UsernameOrEmailNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم أو كلمة المرور غير صحيحه.
        /// </summary>
        internal static string UserNameOrPasswordNotCorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير مصرح له بالدخول.
        /// </summary>
        internal static string UserNotAuthorised {
            get {
                return ResourceManager.GetString("UserNotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم عير موجود في النظام.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم موجود بالنظام لا يمكن حذفه.
        /// </summary>
        internal static string UserUsedCanntDelete {
            get {
                return ResourceManager.GetString("UserUsedCanntDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تصميم لتذكرة المراجعة, يرجى مراجعة مدير النظام.
        /// </summary>
        internal static string VisitTicketNotAvailable {
            get {
                return ResourceManager.GetString("VisitTicketNotAvailable", resourceCulture);
            }
        }
    }
}
