INSERT INTO [SchemaName].[AspNetUsers] ([Id], [Email], [EmailConfirmed], [PasswordHash], [SecurityStamp], [PhoneNumber], [PhoneNumberConfirmed], [TwoFactorEnabled], [LockoutEndDateUtc], [LockoutEnabled], [AccessFailedCount], [UserName]) VALUES (N'4562b74d-1016-42db-8bac-5cbe0efc5743', N'ahmadas@sssprocess.com', 1, N'APfrZb31hJbQJJhwwxR3M8riCZx1ytEsKczB/zV/34SvfQ5f4CTXljFSqZ3UUhqjTw==', N'1ffb1533-dbed-4e8c-aed8-3a97d8414202', N'962796958630', 0, 0, NULL, 1, 0, N'NasserKh')

INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name.ar', N'«·≈”„ »«·⁄—»Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name.ar', N'Arabic Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name.en', N'«·≈”„ »«·≈‰Ã·Ì“Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name.en', N'English Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.NameRequired.ar', N'√œŒ· «·≈”„ »«·⁄—»Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.NameRequired.ar', N'Enter Arabic Name', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.NameRequired.en', N'√œŒ· «·≈”„ »«·≈‰Ã·Ì“Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.NameRequired.en', N'Enter English Name', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.MandatoryFields', N'√œŒ· Ã„Ì⁄ «·ÕﬁÊ· «·≈·“«„Ì…', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.MandatoryFields', N'Enter All Mandatory Fields', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DateBetween', N'«· «—ÌŒ »Ì‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DateBetween', N'Date Between', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserInformations', N'»Ì«‰«  «·‘Œ’ «·„›Ê÷', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserInformations', N'Delegated User Informations', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedName.ar', N'≈”„ «·‘Œ’ »«·⁄—»Ì ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedName.ar', N'Arabic Delegated Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedName.en', N'≈”„ «·‘Œ’ »«·≈‰Ã·Ì“Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedName.en', N'English Delegated Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedNameRequired.ar', N'√œŒ· ≈”„ «·‘Œ’ »«·⁄—»Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedNameRequired.ar', N'Enter Arabic Delegated  Name', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedNameRequired.en', N'√œŒ· ≈”„ «·‘Œ’ »«·≈‰Ã·Ì“Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedNameRequired.en', N'Enter English Delegated  Name', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Save', N'Õ›Ÿ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Save', N'Save', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetButton', N'√⁄œ «·ﬂ «»…', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetButton', N'Clear Inputs', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Edit', N' ⁄œÌ·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Edit', N'Edit', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Cancel', N'≈·€«¡', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Cancel', N'Cancel', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name', N'«·≈”„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Name', N'Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Number', N'«·—ﬁ„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Number', N'Number', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ToDateCompare', N'»œ«Ì… «· «—ÌŒ ÌÃ» √‰  ﬂÊ‰ √ﬁ· „‰ ‰Â«Ì… «· «—ÌŒ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ToDateCompare', N'Begin date must be less than end date', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ToDateRequired', N'√œŒ·  «—ÌŒ «·‰Â«Ì…', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ToDateRequired', N'Enter end date', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.FromDateRequired', N'√œŒ·  «—ÌŒ «·»œ«Ì…', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.FromDateRequired', N'Enter begin date', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.OrgUnitsCount', N'⁄œœ «·≈œ«—« ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.OrgUnitsCount', N'Departments Count', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.UsersCount', N'⁄œœ «·„” Œœ„Ì‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.UsersCount', N'Users Count', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserName', N'≈”„ «·œŒÊ· ≈·Ï «·‰Ÿ«„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserName', N'Login To System UserName', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserNameRequired', N' √œŒ· ≈”„ «·œŒÊ· ≈·Ï «·‰Ÿ«„', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedUserNameRequired', N'Enter login to system userName', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedMobile', N'—ﬁ„ «·ÃÊ«·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedMobile', N'Mobile Number', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedMobileRequired', N' √œŒ· —ﬁ„ «·ÃÊ«·', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedMobileRequired', N'Enter mobile number', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedEmail', N'«·»—Ìœ «·≈·ﬂ —Ê‰Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedEmail', N'Email', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedEmailRequired', N'√œŒ· «·»—Ìœ «·≈·ﬂ —Ê‰Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DelegatedEmailRequired', N'Enter email', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanant.DelegatedEmailExpresssion', N'√œŒ· «·»—Ìœ «·≈·ﬂ —Ê‰Ì »«·‘ﬂ· ’ÕÌÕ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanant.DelegatedEmailExpresssion', N'Correct the email', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.Delete', N'Õ–›', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.Delete', N'Delete', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Tenant', N'«·⁄„Ì·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Tenant', N'Client', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Tenants', N'«·⁄„·«¡', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Tenants', N'Clients', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostName', N'≈”„ «·„÷Ì›', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostName', N'Host Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostNameRequired', N'√œŒ· ≈”„ «·„÷Ì›', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostNameRequired', N'Enter host name', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DeleteSucceeded', N' „  ⁄„·Ì… «·Õ–› »‰Ã«Õ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DeleteSucceeded', N'Delete Succeeded', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.UpdateSucceeded', N' „ ⁄„·Ì… «· ⁄œÌ· »‰Ã«Õ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.UpdateSucceeded', N'Update Succeeded', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.AddSucceeded', N' „  ⁄„·Ì… «·≈÷«›… »‰Ã«Õ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.AddSucceeded', N'Add Succeeded', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Wellcome', N'„—Õ»« »ﬂ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Wellcome', N'Wellcome', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.UserName', N'«”„ «·„” Œœ„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.UserName', N'User Name', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Password', N'—„“ «·œŒÊ·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Password', N'Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.ForgetPassword', N'‰”Ì  ﬂ·„… «·„—Ê—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.ForgetPassword', N'Forget Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Enter', N'«·œŒÊ·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Enter', N'Enter', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Title', N'„—«”·« ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Title', N'eMorasalate', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Reset', N'≈⁄«œ…  ⁄ÌÌ‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Reset', N'Reset', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Password', N'ﬂ·„… «·„—Ê—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Password', N'Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.NewPassword', N'—„“ «·œŒÊ· «·ÃœÌœ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.NewPassword', N'New Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.ReWritePassword', N'≈⁄«œ… ﬂ «»… —„“ «·œŒÊ· «·ÃœÌœ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.ReWritePassword', N'Confirm New Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Code', N'—„“ «· ÊÀÌﬁ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Code', N'Varification Code', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Reset', N'≈⁄«œ…  ⁄ÌÌ‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepTwo.Reset', N'Reset', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Cancel', N'≈·€«¡', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Cancel', N'Cancel', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.ResetPassword', N'≈⁄«œ…  ⁄ÌÌ‰ ﬂ·„… «·„—Ê—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.ResetPassword', N'Reset Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Request', N'ÿ·»', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Request', N'Request', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Username', N'«”„ «·„” Œœ„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Username', N'Username', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Email', N'«·»—Ìœ «·≈·ﬂ —Ê‰Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Email', N'Email', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Reset', N'≈⁄«œ…  ⁄ÌÌ‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.ResetPasswordStepOne.Reset', N'Reset', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.RememberMe', N'Õ›Ÿ „⁄·Ê„«  «·œŒÊ·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.RememberMe', N'Remember Me', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.PleaseEnter', N'° «·—Ã«¡ «·œŒÊ·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.PleaseEnter', N'Enter', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Layout.Year', N'1437', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Layout.Year', N'1437', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.AboutUs', N'„‰ ‰Õ‰', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.AboutUs', N'About Us', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Privacy', N'«·Œ’Ê’Ì…', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.Privacy', N'Privacy', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.ContactUs', N'« ’· »‰«', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Login.ContactUs', N'Contact Us', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.Close', N'Close', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.Close', N'≈€·«ﬁ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanent.Login.InvalidCredentials', N'«·—Ã«¡ «· √ﬂœ „‰ √”„ «·„” Œœ„ √Ê —„“ «·œŒÊ·', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanent.Login.InvalidCredentials', N'Please make sure the user name and access code', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Login.PasswordRequired', N'√œŒ· —„“ «·œŒÊ·', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Login.PasswordRequired', N'Enter Password', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Login.UserNameRequired', N'√œŒ· «”„ «·„” Œœ„', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Login.UserNameRequired', N' Enter UserName', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.EmailRequired', N'√œŒ· «·»—Ìœ «·«·ﬂ —Ê‰Ì', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.EmailRequired', N'Enter Email ', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.EmailSent', N' „ «—”«· «·ÿ·» «·Ï «·»—Ìœ «·«·ﬂ —Ê‰Ì', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.EmailSent', N'Request Sent to the Email', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.Cancel', N'≈·€«¡', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.Cancel', N'Cancel', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.NewPasswordRequierd', N'√œŒ· —„“ «·œŒÊ· «·ÃœÌœ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.NewPasswordRequierd', N'Enter New Password', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.ReNewPasswordRequierd', N'√œŒ·  √ﬂÌœ —„“ «·œŒÊ· «·ÃœÌœ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.ReNewPasswordRequierd', N'Enter Confirm Password', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.CodeRequierd', N'√œŒ· —„“ «· ÊÀÌﬁ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.CodeRequierd', N'Enter the varification code', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.ReNewPasswordCompare', N'€Ì— „ÿ«»ﬁ ·—„“ «·œŒÊ· «·ÃœÌœ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.ReNewPasswordCompare', N'Not Match with the New Password', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.Succeeded', N' „  «·⁄„·Ì… »‰Ã«Õ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPasswordStepTwo.Succeeded', N'operation accomplished successfully', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Localization.TextExpression', N'ÌÃ» ≈œŒ«· √Õ—› ›ﬁÿ', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Localization.TextExpression', N'Must enter just characters', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DeleteMessage', N'Â· √‰  „ √ﬂœ „‰ ⁄„·Ì… «·Õ–›ø', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.DeleteMessage', N'Are you sure from delete operation?', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.DeleteMassage', N'Â· √‰  „ √ﬂœ „‰ ⁄„·Ì… «·Õ–›ø', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.DeleteMassage', N'Are you sure from delete operation?', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.EmptyText', N'·« ÌÊÃœ ‰ «∆Ã ··⁄—÷', N'ar', N'Resources', N'', NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Grid.EmptyText', N'There are no items to display', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UsernameRequired', N'√œŒ· «”„ «·„” Œœ„', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UsernameRequired', N'Enter Username', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.Yes', N'‰⁄„', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.Yes', N'Yes', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.No', N'·«', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.Dialog.No', N'No', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.CopyRightFor', N'Ã„Ì⁄ «·ÕﬁÊﬁ „Õ›ÊŸ… ·œÏ ‘—ﬂ… ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.CopyRightFor', N'Copyright for', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.CompanyName', N'√‰Ÿ„… «·Œœ„«  «·«„‰… · ﬁ‰Ì… «·„⁄·Ê„«  «·„ÕœÊœ…', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.CompanyName', N'SSSIT', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostNameExpresssion', N'√œŒ· ≈”„ «·„÷Ì› »«·‘ﬂ· «·’ÕÌÕ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.HostNameExpresssion', N'Correct the host name ', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.SendResetEmail', N'≈⁄«œ… ≈—”«·  ⁄ÌÌ‰ ﬂ·„… «·”—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.SendResetEmail', N'Resend Reset Password', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.SendResetEmailSucceed', N' „  ⁄„·Ì… «·≈—”«· »‰Ã«Õ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.SendResetEmailSucceed', N'Sent operation succeeded', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Activate', N' ›⁄Ì·', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tenant.Activate', N'Activate', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UserNameNotValid', N'«”„ «·„” Œœ„ €Ì— ’ÕÌÕ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UserNameNotValid', N'User name not valid', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UserEmailNotValid', N'«·»—Ìœ «·«·ﬂ —Ê‰Ì €Ì— ’ÕÌÕ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Global.ResetPassword.UserEmailNotValid', N'Email not valid', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanent.Login.Lockout', N' „ ≈€·«ﬁ Â–« «·Õ”«» ° Ì—ÃÏ ≈⁄«œ… «·„Õ«Ê·… ·«Õﬁ«.', N'ar', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'Tanent.Login.Lockout', N'This account has been locked out, please try again later.', N'en', N'Validation', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'User.Tenant.UploadLogo', N' Õ„Ì· «·‘⁄«—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'User.Tenant.UploadLogo', N'Upload Logo', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'User.Tenant.Logo', N'«·‘⁄«—', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'User.Tenant.Logo', N'Logo', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'UserTenant', N'«·„” Œœ„Ì‰ ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'UserTenant', N'Users Tenant', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'AddUser', N'«÷«›… „” Œœ„ ', N'ar', N'Resources', NULL, NULL, NULL, NULL, NULL)
INSERT INTO [SchemaName].[Resources] ([ResourceId], [Value], [Culture], [ResourceSet], [Type], [BinFile], [TextFile], [Filename], [Comment]) VALUES (N'AddUser', N'Add user', N'en', N'Resources', NULL, NULL, NULL, NULL, NULL)

SET IDENTITY_INSERT [SchemaName].[TenantLocalizationIdentifiers] ON
INSERT INTO [SchemaName].[TenantLocalizationIdentifiers] ([Id], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (1152, GETDATE(), -1, NULL, NULL)
INSERT INTO [SchemaName].[TenantLocalizationIdentifiers] ([Id], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (1153, GETDATE(), -1, NULL, NULL)
SET IDENTITY_INSERT [SchemaName].[TenantLocalizationIdentifiers] OFF

SET IDENTITY_INSERT [SchemaName].[TenantLookups] ON
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (3, 38, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (6, 38, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (7, 34, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (8, 1, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (10, 2, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (11, 0, 1, 1, NULL, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantLookups] ([Id], [CategoryId], [IsActive], [Sort], [EnumReference], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (12, 1, 1, 2, NULL, GETDATE(), NULL, NULL, NULL)
SET IDENTITY_INSERT [SchemaName].[TenantLookups] OFF

SET IDENTITY_INSERT [SchemaName].[TenantCultures] ON
INSERT INTO [SchemaName].[TenantCultures] ([Id], [ShortName], [NameId], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (1, N'ar', 3, GETDATE(), NULL, NULL, NULL)
INSERT INTO [SchemaName].[TenantCultures] ([Id], [ShortName], [NameId], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy]) VALUES (3, N'en', 6, GETDATE(), NULL, NULL, NULL)
SET IDENTITY_INSERT [SchemaName].[TenantCultures] OFF

--SET IDENTITY_INSERT [SchemaName].[Tenants] ON
--INSERT INTO [SchemaName].[Tenants] ([Id], [DatabaseName], [HostName], [FromDate], [FromDateH], [ToDate], [ToDateH], [OrgUnitsCount], [UsersCount], [DelegatedUserName], [DelegatedEmail], [DelegatedMobile], [IsDeleted], [IsActive], [YesserCertificate], [YesserCode], [YesserSourceID], [YesserServiceID], [YesserSourceName], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [DelegatedName_Id], [Name_Id]) VALUES (1074, N'DB_1', N'HN_1', GETDATE(), N'2015/01/01', GETDATE(), N'2015/01/01', NULL, NULL, N'Test_1', N'ttt@t.com', N'34534534534', 0, 1, NULL, NULL, NULL, NULL, NULL, GETDATE(), -1, NULL, NULL, 1152, 1153)
--SET IDENTITY_INSERT [SchemaName].[Tenants] OFF

SET IDENTITY_INSERT [SchemaName].[TenantLocalizations] ON
INSERT INTO [SchemaName].[TenantLocalizations] ([Id], [CultureId], [Text], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [LocalizationIdentifier_Id], [TenantLocalizationIdentifier_Id]) VALUES (1302, 1, N'Database_1', GETDATE(), -1, NULL, NULL, 1153, 1153)
SET IDENTITY_INSERT [SchemaName].[TenantLocalizations] OFF

SET IDENTITY_INSERT [SchemaName].[TenantLookupLocalizations] ON
INSERT INTO [SchemaName].[TenantLookupLocalizations] ([Id], [Text], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [Culture_Id], [Lookup_Id]) VALUES (19, N'

<html xmlns=''http://www.w3.org/1999/xhtml''>
<head>
<title></title>
</head>
<body style=''direction:rtl;''>
<div style=''text-align:right;''></div>
<br /><br />
<div style=''border-top:3px solid #22BCE5''>&nbsp;</div>
<div style='' text-align:right; font-family:Tahoma;font-size:14px''>

  ⁄“Ì“Ì «·„” Œœ„ <span>{UserName}</span>·ﬁœ  „ «‰‘«¡ „” Œœ„ ÃœÌœ ·ﬂ ›Ì ‰Ÿ«„ „—«”·«    
 </div>
 <div style='' text-align:right; font-family:Tahoma;font-size:14px''>
 · ›⁄Ì· «·„” Œœ„ Ê«·»œ¡ »«” Œœ«„ «·‰Ÿ«„ <a href=''{Url}'' >«‰ﬁ— Â‰«</a> 
 <div> 
</body>
</html>', GETDATE(), NULL, NULL, NULL, 1, 7)
INSERT INTO [SchemaName].[TenantLookupLocalizations] ([Id], [Text], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [Culture_Id], [Lookup_Id]) VALUES (20, N'<html xmlns=''http://www.w3.org/1999/xhtml''>
<head>
<title></title>
</head>
<body style=''direction:ltr;''>
<div style=''text-align:left;''></div>
<br /><br />
<div style=''border-top:3px solid #22BCE5''>&nbsp;</div>
<div style='' text-align:right; font-family:Tahoma;font-size:14px''>
Dear User <span>{UserName}</span> A New User Has been Created for You 
 </div>
 <div style='' text-align:right; font-family:Tahoma;font-size:14px''>
 To Activate the user and Star Using eMorasalat System <a href=''{Url}'' >Click Here</a>

 </div> 
</body>
</html>', GETDATE(), NULL, NULL, NULL, 3, 7)
INSERT INTO [SchemaName].[TenantLookupLocalizations] ([Id], [Text], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [Culture_Id], [Lookup_Id]) VALUES (24, N'„” Œœ„ ÃœÌœ ›Ì ‰Ÿ«„ „—«”·« ', GETDATE(), NULL, NULL, NULL, 1, 8)
INSERT INTO [SchemaName].[TenantLookupLocalizations] ([Id], [Text], [CreatedOn], [CreatedBy], [ModefiedOn], [ModefiedBy], [Culture_Id], [Lookup_Id]) VALUES (25, N'New User in eMorasalat System', GETDATE(), NULL, NULL, NULL, 3, 8)
SET IDENTITY_INSERT [SchemaName].[TenantLookupLocalizations] OFF

