#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/_AnnProperties.cshtml")]
    public partial class _Views_DocoNut__AnnProperties_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut__AnnProperties_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div id=\"annModal\" class=\"modal fade\" role=\"dialog\">\r\n    <div class=\"modal-dialo" +
"g modal-lg\" style=\"width:100%\">\r\n\r\n        <!-- Modal content-->\r\n        <div c" +
"lass=\"modal-content\">\r\n            <div class=\"modal-header\">\r\n                <" +
"h4 class=\"modal-title\">Properties</h4>\r\n                <button type=\"button\" cl" +
"ass=\"close\" data-dismiss=\"modal\">&times;</button>\r\n            </div>\r\n         " +
"   <div class=\"modal-body\">\r\n\r\n                <div class=\"row\">\r\n              " +
"      <div class=\"col-lg-4 col-md-6 col-sm-12 col-sm-12\">\r\n\r\n                   " +
"     <div class=\"form-group\">\r\n                            <label>Back color:</l" +
"abel>\r\n                            <input type=\"text\" class=\"form-control\" id=\"a" +
"nnbackColor\" />\r\n\r\n\r\n\r\n                            <label>Border&nbsp;color:</la" +
"bel>\r\n                            <input type=\"text\" class=\"form-control\" id=\"an" +
"nborderColor\" />\r\n\r\n                            <label>Border&nbsp;width:</label" +
">\r\n                            <input type=\"text\" class=\"form-control\" id=\"annbo" +
"rderWidth\" />\r\n\r\n\r\n\r\n                            <label>Show&nbsp;Border</label>" +
"\r\n                            <input type=\"text\" class=\"form-control\" id=\"annsho" +
"wBorder\" />\r\n\r\n\r\n\r\n                            <label>Opacity</label>\r\n         " +
"                   <input type=\"text\" class=\"form-control\" id=\"annOpactiy\" />\r\n\r" +
"\n\r\n\r\n                            <label>Rotate</label>\r\n                        " +
"    <input type=\"text\" class=\"form-control\" id=\"annRotate\" />\r\n\r\n\r\n\r\n           " +
"                 <label>Can Rotate</label>\r\n                            <input t" +
"ype=\"text\" class=\"form-control\" id=\"annCanRotate\" />\r\n                        </" +
"div>\r\n\r\n                    </div>\r\n                    <div class=\"col-lg-4 col" +
"-md-6 col-sm-12 col-sm-12\">\r\n\r\n                        <div class=\"form-group\">\r" +
"\n                            <label>Title</label>\r\n                            <" +
"input type=\"text\" class=\"form-control\" id=\"annTitle\" />\r\n\r\n\r\n\r\n                 " +
"           <label>Show Title</label>\r\n                            <input type=\"t" +
"ext\" class=\"form-control\" id=\"annshowTitle\" />\r\n\r\n\r\n\r\n                          " +
"  <label>Title color</label>\r\n                            <input type=\"text\" cla" +
"ss=\"form-control\" id=\"anntitleColor\" />\r\n\r\n\r\n\r\n                            <labe" +
"l>Title Font Size</label>\r\n                            <input type=\"text\" class=" +
"\"form-control\" id=\"anntitleFontSize\" />\r\n\r\n\r\n\r\n\r\n                            <la" +
"bel>Note/Url</label>\r\n                            <input type=\"text\" class=\"form" +
"-control\" id=\"annNote\" />\r\n\r\n\r\n\r\n                            <label>Show Note</l" +
"abel>\r\n                            <input type=\"text\" class=\"form-control\" id=\"a" +
"nnshowNote\" />\r\n\r\n\r\n\r\n                            <label>Text align</label>\r\n   " +
"                         <input type=\"text\" class=\"form-control\" id=\"anntextAlig" +
"n\" />\r\n\r\n                        </div>\r\n\r\n                    </div>\r\n\r\n       " +
"             <div class=\"col-lg-4 col-md-6 col-sm-12 col-sm-12\">\r\n\r\n            " +
"            <div class=\"form-group\">\r\n\r\n\r\n                            <label>Arr" +
"ow Direction</label>\r\n                            <input type=\"text\" class=\"form" +
"-control\" id=\"annarrowDirection\" />\r\n\r\n                            <label>Line V" +
"ertical</label>\r\n                            <input type=\"text\" class=\"form-cont" +
"rol\" id=\"annlineVertical\" />\r\n\r\n\r\n                            <label>Burn</label" +
">\r\n                            <input type=\"text\" class=\"form-control\" id=\"annBu" +
"rn\" />\r\n\r\n\r\n                            <label>Locked</label>\r\n                 " +
"           <input type=\"text\" class=\"form-control\" id=\"annLocked\" />\r\n\r\n\r\n      " +
"                      <label>z-Index</label>\r\n                            <input" +
" type=\"text\" class=\"form-control\" id=\"annzindex\" />\r\n\r\n\r\n                       " +
"     <label>Author</label>\r\n                            <input type=\"text\" class" +
"=\"form-control\" id=\"annAuthor\" />\r\n\r\n                        </div>\r\n           " +
"         </div>\r\n                </div>\r\n\r\n            </div>\r\n            <div " +
"class=\"modal-footer\">\r\n                <button type=\"button\" class=\"btn btn-prim" +
"ary\" onclick=\"SaveAnnotationData();\">Save</button>\r\n                <button type" +
"=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n         " +
"   </div>\r\n        </div>\r\n\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
