#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\DocoNut\_FileUpload.cshtml"
    using MCS.DoconutMVC.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/_FileUpload.cshtml")]
    public partial class _Views_DocoNut__FileUpload_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut__FileUpload_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral(@"<div id=""myModal"" class=""modal fade"" role=""dialog"">
    <div class=""modal-dialog"">

        <!-- Modal content-->
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h4 class=""modal-title"" style=""color:#333738"">
                    ");


            
            #line 9 "..\..\Views\DocoNut\_FileUpload.cshtml"
               Write(Html.GlobalResource("UploadDocument"));

            
            #line default
            #line hidden
WriteLiteral(@"
                </h4>
                <button type=""button"" class=""close"" data-dismiss=""modal"">&times;</button>
            </div>
            <div class=""modal-body"">


                <div id=""dropZoneForm"" class=""dropzone"">
                    <div class=""dz-message"">
                        ");


            
            #line 18 "..\..\Views\DocoNut\_FileUpload.cshtml"
                   Write(Html.GlobalResource("ClickOrDragToUpload"));

            
            #line default
            #line hidden
WriteLiteral(@"
                    </div>
                    <div>
                        <div class=""fallback"">
                            <input name=""file"" id=""file"" type=""file"" />
                        </div>
                    </div>
                </div>


            </div>
            <div class=""modal-footer"">
                <button type=""button"" class="" btn btn-st1 btn-lg"" data-dismiss=""modal"">
                    ");


            
            #line 31 "..\..\Views\DocoNut\_FileUpload.cshtml"
               Write(Html.GlobalResource("Exitbtn"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </button>\r\n            </div>\r\n        </div>\r\n\r\n    </div>\r\n</" +
"div>");


        }
    }
}
#pragma warning restore 1591
