#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\DocoNut\_Footer.cshtml"
    using MCS.DoconutMVC.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/_Footer.cshtml")]
    public partial class _Views_DocoNut__Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut__Footer_cshtml()
        {
        }
        public override void Execute()
        {

WriteLiteral("<nav class=\"nav-toolbar-bottom text-center\">\r\n    <button type=\"button\" class=\"bt" +
"n btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n            title=" +
"");


            
            #line 4 "..\..\Views\DocoNut\_Footer.cshtml"
             Write(Html.GlobalResource("TheNext"));

            
            #line default
            #line hidden
WriteLiteral(" onclick=\"objctlDoc.Next(true);\">\r\n        <i class=\"fas fa-angle-right\"></i>\r\n  " +
"  </button>\r\n    <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tool" +
"tip\" data-placement=\"bottom\"\r\n            title=");


            
            #line 8 "..\..\Views\DocoNut\_Footer.cshtml"
             Write(Html.GlobalResource("TheLast"));

            
            #line default
            #line hidden
WriteLiteral(" onclick=\"objctlDoc.GotoPage(parseInt(objctlDoc.TotalPages()));\">\r\n        <i cla" +
"ss=\"fas fa-angle-double-right\" ></i>\r\n    </button>\r\n\r\n    <button type=\"button\"" +
" class=\"btn btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n        " +
"    title=");


            
            #line 13 "..\..\Views\DocoNut\_Footer.cshtml"
             Write(Html.GlobalResource("TheFirst"));

            
            #line default
            #line hidden
WriteLiteral(" onclick=\"objctlDoc.GotoPage(1);\">\r\n        <i class=\"fas fa-angle-double-left\"><" +
"/i>\r\n    </button>\r\n    <button type=\"button\" class=\"btn btn-default\" data-toggl" +
"e=\"tooltip\" data-placement=\"bottom\"\r\n            title=");


            
            #line 17 "..\..\Views\DocoNut\_Footer.cshtml"
             Write(Html.GlobalResource("ThePrevious"));

            
            #line default
            #line hidden
WriteLiteral(" onclick=\"objctlDoc.Next(false);\">\r\n        <i class=\"fas fa-angle-left\"></i>\r\n  " +
"  </button>\r\n</nav>\r\n");


        }
    }
}
#pragma warning restore 1591
