#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;

#line 40 "..\..\Views\DocoNut\_Menu.cshtml"
    using MCS.DoconutMVC.Helpers;

#line default
#line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/_Menu.cshtml")]
    public partial class _Views_DocoNut__Menu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut__Menu_cshtml()
        {
        }
        public override void Execute()
        {
            WriteLiteral(@"<style>
    .toolbar {
        z-index: 100;
        position: relative;
    }

    .btn-group {
        margin-left: 5px;
    }

        .btn-group button {
            font-size: 20px !important;
        }

    .btnAnnCancel, .btnAnnSave {
        color: #333;
        background-color: #fff;
        border-color: #ccc;
        display: none;
        padding: 6px 12px;
        margin: 5px;
        font-size: 14px;
        font-weight: 400;
        line-height: 1.42857143;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
        -ms-touch-action: manipulation;
        touch-action: manipulation;
        cursor: pointer;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
        background-image: none;
        border: 1px solid transparent;
        border-radius: 4px;
    }
</style>
");

            WriteLiteral(@"<script>   
    setInterval(function () {  $('#btnEditAnnotation').show(); }, 3500);
    </script>
");
            WriteLiteral("\r\n\r\n");



#line 43 "..\..\Views\DocoNut\_Menu.cshtml"

            bool annotationonly = Request.QueryString.AllKeys.Contains("annotationonly") ? Convert.ToBoolean(Request.QueryString["annotationonly"]) : false;
            bool showbarcode = Request.QueryString.AllKeys.Contains("showbarcode") ? Convert.ToBoolean(Request.QueryString["showbarcode"]) : true;
            bool printDocumentPermission = Convert.ToBoolean(Session["PrintDocumentPermission"].ToString());
            bool deleteDocumentPermission = Convert.ToBoolean(Session["DeleteDocumentPermission"].ToString());
            bool colorDocumentPermission = Convert.ToBoolean(Session["ColorDocumentPermission"].ToString());
            bool annotationDocumentPermission = Convert.ToBoolean(Session["AnnotactionDocumentPermission"].ToString());
            bool printWithoutWaterMark = Convert.ToBoolean(Session["WatermarkPermissions"].ToString());


#line default
#line hidden
            WriteLiteral("<div class=\"toolbar\">\r\n");



#line 52 "..\..\Views\DocoNut\_Menu.cshtml"
            if (!annotationonly)
            {


#line default
#line hidden
                WriteLiteral("        <div class=\"btn-group\">\r\n            <select id=\"ddlUploadMode\" class=\"fo" +
                "rm-control\">\r\n                <option value=\"1\" selected=\"selected\">");



#line 56 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("RegulerArchiving"));


#line default
#line hidden
                WriteLiteral("</option>\r\n                <option value=\"2\">");



#line 57 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("ReplacePage"));


#line default
#line hidden
                WriteLiteral("</option>\r\n                <option value=\"3\">");



#line 58 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("PrePage"));


#line default
#line hidden
                WriteLiteral("</option>\r\n                <option value=\"4\">");



#line 59 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("AfterPage"));


#line default
#line hidden
                WriteLiteral("</option>\r\n            </select>\r\n        </div>\r\n");



                WriteLiteral("        <div class=\"btn-group\" role=\"group\" aria-label=\"Acquire Image\">\r\n        " +
                "    ");



                WriteLiteral("\r\n            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\"" +
                " data-placement=\"bottom\"\r\n                    title=");



#line 65 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("UploadFileToolTip"));


#line default
#line hidden
                WriteLiteral(" onclick=\"OpenUpload();\" data-title=\"Upload\">\r\n                <i class=\"fas fa-f" +
                "ile-upload\"></i>\r\n            </button>\r\n            ");



                WriteLiteral("\r\n");



#line 69 "..\..\Views\DocoNut\_Menu.cshtml"
                if (!Request.QueryString.AllKeys.Contains("hidecontrols"))
                {


#line default
#line hidden
                    WriteLiteral("                <button type=\"button\" class=\"btn btn-default\" data-toggle=\"toolti" +
                    "p\" data-placement=\"bottom\"\r\n                        title=");



#line 72 "..\..\Views\DocoNut\_Menu.cshtml"
                    Write(Html.GlobalResource("ScannerToolTip"));


#line default
#line hidden
                    WriteLiteral(" onclick=\"AcquireImage(1);\" data-title=\"Scan\">\r\n                    <i class=\"fas" +
                    " fa-file\"></i>\r\n                </button>\r\n");



#line 75 "..\..\Views\DocoNut\_Menu.cshtml"
                    if (colorDocumentPermission)
                    {


#line default
#line hidden
                        WriteLiteral("                    <button type=\"button\" class=\"btn btn-default\" data-toggle=\"to" +
                        "oltip\" data-placement=\"bottom \"\r\n                            title=");



#line 78 "..\..\Views\DocoNut\_Menu.cshtml"
                        Write(Html.GlobalResource("ScannerWithColorsToolTip"));


#line default
#line hidden
                        WriteLiteral(" onclick=\"AcquireImage(2);\" data-title=\"Color Scan\">\r\n                        <i " +
                        "class=\"fas fa-fill-drip\" style=\"background-image:linear-gradient(141deg, #e52f4b" +
                        "b0 0%, #cee510 44%, #09afed 75%)\"></i>\r\n                    </button>\r\n");



#line 81 "..\..\Views\DocoNut\_Menu.cshtml"
                    }
                }


#line default
#line hidden


#line 83 "..\..\Views\DocoNut\_Menu.cshtml"



#line default
#line hidden
                WriteLiteral("        </div>\r\n");



#line 95 "..\..\Views\DocoNut\_Menu.cshtml"
            }


#line default
#line hidden
            WriteLiteral("\r\n\r\n    <div class=\"btn-group\" role=\"group\" aria-label=\"Zoom\">\r\n        ");



            WriteLiteral("\r\n        <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" dat" +
            "a-placement=\"bottom\"\r\n                title=");



#line 101 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("ZoomInToolTip"));


#line default
#line hidden
            WriteLiteral(" onclick=\"objctlDoc.Zoom(true);\" data-title=\"Zoom In\">\r\n            <i class=\"fas" +
            " fa-search-plus\"></i>\r\n        </button>\r\n        <button type=\"button\" class=\"b" +
            "tn btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n                t" +
            "itle=");



#line 105 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("ZoomOutToolTip"));


#line default
#line hidden
            WriteLiteral(" onclick=\"objctlDoc.Zoom(false);\" data-title=\"Zoom Out\">\r\n            <i class=\"f" +
            "as fa-search-minus\"></i>\r\n        </button>\r\n    </div>\r\n\r\n    <div class=\"btn-g" +
            "roup\" role=\"group\" aria-label=\"Signature and Stamp and Barcode\">\r\n        ");



            WriteLiteral("\r\n        <button type=\"button\" class=\"btn Edit btn-default\" data-toggle=\"tooltip" +
            "\" data-placement=\"bottom\"\r\n                title=");



#line 113 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("EditToolTip"));


#line default
#line hidden
            //            WriteLiteral(" onclick=\"RotateDocument();\" data-title=\"Rotate\">\r\n            <i class=\"f" +
            //            "as fa-rotate-90\"></i>\r\n        </button>\r\n    </div>\r\n\r\n    <div class=\"btn-g" +
            //            "roup\" role=\"group\" aria-label=\"Rotate Document\">\r\n        ");



            //            WriteLiteral("\r\n        <button type=\"button\" class=\"btn Edit btn-default\" data-toggle=\"tooltip" +
            //            "\" data-placement=\"bottom\"\r\n                title=");



            //#line 113 "..\..\Views\DocoNut\_Menu.cshtml"
            //            Write(Html.GlobalResource("EditToolTip"));



            //#line default
            //#line hidden
            WriteLiteral(" onclick=\"StartAnnotation();\"  id=\"btnEditAnnotation\" style=\"display:none;\" data-title=\"Edit\">\r\n            <i class=\"fas fa-ed" +
"it\"></i>\r\n        </button>\r\n        ");



            WriteLiteral("\r\n        <button id=\"btnAddSign\" style=\"display:none;\" type=\"button\" class=\"btn " +
            "btnEdit btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n            " +
            "    title=");



#line 118 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("SignatureToolTip"));


#line default
#line hidden
            WriteLiteral(@" onclick=""ImageSignature();"" data-title=""Signature"">
            <i class=""fas fa-signature""></i>
        </button>
        <button id=""btnAddStamp"" style=""display:none;"" type=""button"" class=""btn btnEdit btn-default"" data-toggle=""tooltip"" data-placement=""bottom""
                title=");



#line 122 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("StampToolTip"));


#line default
#line hidden
            WriteLiteral(" onclick=\"ImageStamp();\" data-title=\"Stamp\">\r\n            <i class=\"fas fa-stamp\"" +
            "></i>\r\n        </button>\r\n");



#line 125 "..\..\Views\DocoNut\_Menu.cshtml"
            if (showbarcode)
            {


#line default
#line hidden
                WriteLiteral("            <button id=\"btnAddBarcode\" style=\"display:none;\" type=\"button\" class=" +
                "\"btn  btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n              " +
                "      title=");



#line 128 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("BarcodeToolTip"));


#line default
#line hidden
                WriteLiteral(" onclick=\"ImageBarcode();\" data-title=\"Barcode\">\r\n                <i class=\"fas f" +
                "a-barcode\"></i>\r\n            </button>\r\n");



#line 131 "..\..\Views\DocoNut\_Menu.cshtml"
            }


#line default
#line hidden
            WriteLiteral(@"        <button id=""btnTextNote"" style=""display:none;"" type=""button"" class=""btn  btn-default"" data-toggle=""tooltip"" data-placement=""bottom""
                title=""اضافة نص"" onclick=""AddTextNote();"" data-title=""Barcode"">
            <i class=""fas fas fa-book fa-fw""></i>
        </button>
    </div>
");



#line 137 "..\..\Views\DocoNut\_Menu.cshtml"
            if (annotationDocumentPermission)
            {


#line default
#line hidden
                WriteLiteral("        <div class=\"btn-group\" role=\"group\" aria-label=\"Custom Annotation\" id=\"do" +
                "cViewerAnnotations\" style=\"display:none;\">\r\n            ");



                WriteLiteral("\r\n            <button type=\"button\" class=\"btn btnEdit btn-default AnnotationButt" +
                "on\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n                    title=");



#line 142 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("RectangleToolTip"));


#line default
#line hidden
                WriteLiteral(" data-title=\"rectangle\">\r\n                <i class=\"far fa-square\"></i>\r\n        " +
                "    </button>\r\n            <button type=\"button\" class=\"btn btnEdit btn-default " +
                "AnnotationButton\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n               " +
                "     title=");



#line 146 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("lineToolTip"));


#line default
#line hidden
                WriteLiteral(@" data-title=""line"">
                <i class=""fas fa-grip-lines-vertical""></i>
            </button>
            <button type=""button"" class=""btn btnEdit btn-default AnnotationButton"" data-toggle=""tooltip"" data-placement=""bottom""
                    title=");



#line 150 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("ArrowToolTip"));


#line default
#line hidden
                WriteLiteral(" data-title=\"arrow\">\r\n                <i class=\"fas fa-arrow-right\"></i>\r\n       " +
                "     </button>\r\n            <button type=\"button\" class=\"btn btnEdit btn-default" +
                " AnnotationButton\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n              " +
                "      title=");



#line 154 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("TriangleToolTip"));


#line default
#line hidden
                WriteLiteral(@" data-title=""triangle"">
                <i class=""fas fa-chevron-up"" style=""border-bottom:2px solid #000;""></i>
            </button>
            <button type=""button"" class=""btn btnEdit btn-default AnnotationButton"" data-toggle=""tooltip"" data-placement=""bottom""
                    title=");



#line 158 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("CircleToolTip"));


#line default
#line hidden
                WriteLiteral(" data-title=\"circle\">\r\n                <i class=\"far fa-circle\"></i>\r\n           " +
                " </button>\r\n\r\n            <button type=\"button\" class=\"btn btnEdit btn-default A" +
                "nnotationButton\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n                " +
                "    title=");



#line 163 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("FreehandToolTip"));


#line default
#line hidden
                WriteLiteral(" data-title=\"freehand\">\r\n                <i class=\"fas fa-pen-fancy\"></i>\r\n      " +
                "      </button>\r\n        </div>\r\n");



#line 167 "..\..\Views\DocoNut\_Menu.cshtml"
            }


#line default
#line hidden
            WriteLiteral("\r\n    <div class=\"btn-group\" role=\"group\" aria-label=\"Remove Clean Annotation\">\r\n" +
            "        ");



            WriteLiteral("\r\n        <button id=\"btnDeleteAnnotation\" style=\"display:none;\" type=\"button\" cl" +
            "ass=\"btn btn-default\" data-toggle=\"tooltip\" data-placement=\"bottom\"\r\n           " +
            "     title=\'");



#line 172 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("DeleteToolTip"));


#line default
#line hidden
            WriteLiteral(@"' onclick=""DeleteAnnotations();"">
            <i class=""far fa-trash-alt""></i>
        </button>
        <button id=""btnClearAnnotaions"" style=""display:none;"" type=""button"" class=""btn btn-default"" data-toggle=""tooltip"" data-placement=""bottom""
                title='");



#line 176 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("ClearAnnotationsToolTip"));


#line default
#line hidden
            WriteLiteral("\' onclick=\"ClearAnnotations();\">\r\n            <i class=\"fas fa-eraser\"></i>\r\n    " +
            "    </button>\r\n        <button type=\"button\" class=\"btn btn-default\" data-toggle" +
            "=\"tooltip\" data-placement=\"bottom\"\r\n                title=\'");



#line 180 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("DeletePageToolTip"));


#line default
#line hidden
            WriteLiteral("\' onclick=\"DeletePage();\">\r\n            <i class=\"fas fa-remove\"></i>\r\n        </" +
            "button>\r\n");



#line 183 "..\..\Views\DocoNut\_Menu.cshtml"

            WriteLiteral("            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" d" +
          "ata-placement=\"bottom\"\r\n                    title=\'");

#line 187 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("MovePageUpToolTip"));


#line default
#line hidden
            WriteLiteral("\' onclick=\"ChangePageOrder(true);\">\r\n                <i class=\"fas fa-sort-numeric-up" +
            "\"></i>\r\n            </button>\r\n");



#line 190 "..\..\Views\DocoNut\_Menu.cshtml"





#line default
#line hidden
            WriteLiteral("            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" d" +
            "ata-placement=\"bottom\"\r\n                    title=\'");



#line 187 "..\..\Views\DocoNut\_Menu.cshtml"
            Write(Html.GlobalResource("MovePageDownToolTip"));


#line default
#line hidden
            WriteLiteral("\' onclick=\"ChangePageOrder(false);\">\r\n                <i class=\"fas fa-sort-numeric-down" +
            "\"></i>\r\n            </button>\r\n");



#line 190 "..\..\Views\DocoNut\_Menu.cshtml"

#line default
#line hidden
                WriteLiteral("            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" d" +
                "ata-placement=\"bottom\"\r\n                    title=\'");



#line 186 "..\..\Views\DocoNut\_Menu.cshtml"
                Write(Html.GlobalResource("DeleteDocumentToolTip"));


#line default
#line hidden
                WriteLiteral("\' onclick=\"DeleteDocumentTemp();\">\r\n                <i class=\"fas fa-folder-minus" +
                "\"></i>\r\n            </button>\r\n");



#line 189 "..\..\Views\DocoNut\_Menu.cshtml"



            //#line default
            //#line hidden
            //            WriteLiteral("            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" d" +
            //            "ata-placement=\"bottom\"\r\n                    title=\'");



            //#line 186 "..\..\Views\DocoNut\_Menu.cshtml"
            //            Write(Html.GlobalResource("MovePageUpToolTip"));


            //#line default
            //#line hidden
            //            WriteLiteral("\' onclick=\"ChangePageOrder(true);\">\r\n                <i class=\"fas fa-sort-numeric-up" +
            //            "\"></i>\r\n            </button>\r\n");



            //#line 189 "..\..\Views\DocoNut\_Menu.cshtml"


            //#line default
            //#line hidden
            //            WriteLiteral("            <button type=\"button\" class=\"btn btn-default\" data-toggle=\"tooltip\" d" +
            //            "ata-placement=\"bottom\"\r\n                    title=\'");



            //#line 186 "..\..\Views\DocoNut\_Menu.cshtml"
            //            Write(Html.GlobalResource("MovePageDownToolTip"));


            //#line default
            //#line hidden
            //            WriteLiteral("\' onclick=\"ChangePageOrder(false);\">\r\n                <i class=\"fas fa-sort-numeric-down" +
            //            "\"></i>\r\n            </button>\r\n");



            //#line 189 "..\..\Views\DocoNut\_Menu.cshtml"


#line default
#line hidden
            WriteLiteral("    </div>\r\n</div>\r\n\r\n\r\n");



            WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
