#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MCS.DoconutMVC.Helpers;
    using DoconutViewer;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/_ScanningControl.cshtml")]
    public partial class _Views_DocoNut__ScanningControl_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut__ScanningControl_cshtml()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\DocoNut\_ScanningControl.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden


WriteLiteral("\r\n<div id=\"dwtcontrolContainer2\" style=\"z-index:-1; position: absolute; display:n" +
"one;\"></div>\r\n<script src=\"");


            
            #line 7 "..\..\Views\DocoNut\_ScanningControl.cshtml"
        Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Resources.dynamsoft.webtwain.initiate.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n<script src=\"");


            
            #line 8 "..\..\Views\DocoNut\_ScanningControl.cshtml"
        Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Resources.dynamsoft.webtwain.config.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
