#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;

#line 1 "..\..\Views\DocoNut\Index.cshtml"
    using MCS.DoconutMVC.Helpers;

#line default
#line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/Index.cshtml")]
    public partial class _Views_DocoNut_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut_Index_cshtml()
        {
        }
        public override void Execute()
        {

            WriteLiteral("\r\n\r\n");



#line 4 "..\..\Views\DocoNut\Index.cshtml"

            ViewBag.Title = "Annotations - Doconut Asp.Net MVC Document Viewer";
            Layout = "~/Views/Shared/doconut/_Layout.cshtml";
            bool printDocumentPermission = Session["PrintDocumentPermission"] != null && Convert.ToBoolean(Session["PrintDocumentPermission"].ToString());
            bool DownLoadDocumentPermission = Session["DownLoadDocumentPermission"] != null && Convert.ToBoolean(Session["DownLoadDocumentPermission"].ToString());

            bool printWithoutWaterMark = Convert.ToBoolean(Session["WatermarkPermissions"].ToString());


#line default
#line hidden
            WriteLiteral(@"
<style>
    .form-group label {
        color: gray;
        font-weight: bolder;
        margin-top: .5rem;
        margin-bottom: 0;
    }
</style>

<style>
    .toolbar {
        margin-bottom: 5px;
        color: inherit;
        background-color: none;
        padding-right: 15px;
        padding-left: 15px;
        padding: 5px;
        border-radius: 6px;
        text-align: center;
    }


        .toolbar nav.nav-toolbar-top, .toolbar nav.nav-toolbar-bottom {
            padding: 3px;
        }

    #divDocViewer {
        max-height: calc(526px - 8.7rem);
    }

    .previewBox {
        border: none;
    }
</style>

");


            DefineSection("css", () =>
            {

                WriteLiteral("\r\n    ");



                WriteLiteral("\r\n    ");



#line 47 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.Raw(ViewBag.ViewerCSS));


#line default
#line hidden
                WriteLiteral("\r\n\r\n    <!-- Dropzone (upload) -->\r\n    <link href=\"");



#line 50 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.dropzone.basic.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n    <link href=\"");



#line 51 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.dropzone.dropzone.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n\r\n    <!-- Bootstrap 4 -->\r\n    <link href=\"");



#line 54 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.bootstrap.min.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n    <link href=\"");



#line 55 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.rtl.min.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n    <link href=\"");



#line 56 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.font-awesome.min.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n\r\n\r\n    <link href=\"");



#line 59 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.style.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n    <link href=\"");



#line 60 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Content.User.lib.fontawesome.css.all.css"));


#line default
#line hidden
                WriteLiteral("\" rel=\"stylesheet\" />\r\n");


            });

            WriteLiteral("\r\n\r\n<div class=\"text-center\">\r\n    <div class=\"previewBox\">\r\n        <div class=\"" +
            "row\">\r\n");



#line 66 "..\..\Views\DocoNut\Index.cshtml"
            if (!Request.QueryString.AllKeys.Contains("hidecontrols"))
            {


#line default
#line hidden

#line 68 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.Partial("_Menu"));


#line default
#line hidden

#line 68 "..\..\Views\DocoNut\Index.cshtml"

            }
            if (printDocumentPermission && !Request.QueryString.AllKeys.Contains("hideAllcontrols"))
            {


#line default
#line hidden
                WriteLiteral(@"                <div class=""toolbar"">
                    <div class=""btn-group"">
                        <button id=""btnPrintDocument"" type=""button"" class=""btn btnEdit btn-default"" data-toggle=""tooltip"" data-placement=""bottom""
                                title=");



#line 75 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GlobalResource("PrintDocumentToolTip"));


#line default
#line hidden

                if (!printWithoutWaterMark)
                {
                    WriteLiteral(@" onclick="" alert('سيتم الطباعة مع علامة مائية'); PrintDocument();"" data-title=""Stamp"">
                            <i class=""fas fa-print""></i>
                        </button>
                         ");
                }
                else
                {
                    WriteLiteral(@" onclick=""  alert('سيتم الطباعة بدون علامة مائية'); PrintDocument();"" data-title=""Stamp"">
                            <i class=""fas fa-print""></i>
                        </button>
                       ");
                }


                WriteLiteral(
              "     </div>\r\n");


#line 79 "..\..\Views\DocoNut\Index.cshtml"




#line 84 "..\..\Views\DocoNut\Index.cshtml"
            }
            if (DownLoadDocumentPermission && !Request.QueryString.AllKeys.Contains("hideAllcontrols"))
            {


#line default
#line hidden
                WriteLiteral(@"
                                <div class=""btn-group"">
                                    <button id=""btnDownloadDocument"" type=""button"" class=""btn btnEdit btn-default"" data-toggle=""tooltip"" data-placement=""bottom""
                                            title=");





#line 79 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GlobalResource("DownloadDocumentToolTip"));


#line default
#line hidden
                WriteLiteral(" onclick=\"DownloadDocument(\'");



#line 79 "..\..\Views\DocoNut\Index.cshtml"
                Write(Session["printToken"].ToString());


#line default
#line hidden
                WriteLiteral("\');\" data-title=\"Stamp\">\r\n                            <i class=\"fas fa-download\">" +
                "</i>\r\n                        </button>\r\n                    </div>\r\n           " +
                "     </div>\r\n");



#line 84 "..\..\Views\DocoNut\Index.cshtml"
            }
            WriteLiteral(
           "     </div>\r\n");

#line default
#line hidden
            WriteLiteral("            <div class=\"row\">\r\n            <div class=\"col-xs-12 text" +
"-right wrapper\">\r\n                <div id=\"divDocViewer\" class=\"viewer\" style=\"m" +
"in-height:1300px !important\">\r\n                    <div id=\"div_");



#line 89 "..\..\Views\DocoNut\Index.cshtml"
            Write(ViewBag.ViewerID);


#line default
#line hidden
            WriteLiteral("\"></div>\r\n                    <input type=\"hidden\" id=\"_hdnToken\" />\r\n           " +
            "     </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n<!-- Page" +
            " Content -->\r\n<!-- File upload modal -->\r\n");



#line 99 "..\..\Views\DocoNut\Index.cshtml"
            Write(Html.Partial("_FileUpload"));


#line default
#line hidden
            WriteLiteral("\r\n\r\n<!-- Annotation properties modal -->\r\n");



#line 102 "..\..\Views\DocoNut\Index.cshtml"
            Write(Html.Partial("_AnnProperties"));


#line default
#line hidden
            WriteLiteral("\r\n");



#line 103 "..\..\Views\DocoNut\Index.cshtml"
            if (!Request.QueryString.AllKeys.Contains("hidecontrols"))
            {


#line default
#line hidden

#line 105 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.Partial("_ScanningControl"));


#line default
#line hidden

#line 105 "..\..\Views\DocoNut\Index.cshtml"

            }


#line default
#line hidden
            WriteLiteral("<!-- Footer -->\r\n");



#line 108 "..\..\Views\DocoNut\Index.cshtml"
            Write(Html.Partial("_Footer"));


#line default
#line hidden
            WriteLiteral("\r\n\r\n\r\n");


            DefineSection("scripts", () =>
            {

                WriteLiteral("\r\n    <!-- Viewer header scripts include-->\r\n    ");



#line 113 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.Raw(ViewBag.ViewerScripts));


#line default
#line hidden
                WriteLiteral("\r\n\r\n    <!-- Bootstrap 4 JS -->\r\n    ");



                WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");



#line 117 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.bootstrap.min.js"));


#line default
#line hidden
                WriteLiteral("\"></script>\r\n\r\n    <!-- Touch support for annotations -->\r\n    ");



                WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");



#line 121 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.jquery.ui.touch-punch.min.js"));


#line default
#line hidden
                WriteLiteral("\"></script>\r\n\r\n    <!-- Drop Zone JS (For upload) -->\r\n    <script type=\"text/jav" +
                "ascript\" src=\"");



#line 124 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.dropzone.dropzone.js"));


#line default
#line hidden
                WriteLiteral(@"""></script>


    <script language=""javascript"" type=""text/javascript"">
        Dropzone.autoDiscover = false; // required if using Dropzone

       // Global variables

        var annMode = false;        // the see if annotation mode is ON or not
        var objctlDoc = null;       // Server object id is ""ctlDoc""
        var loader = $("".loader"");
        var isMobile = false;
        var resizing = false;
        var docViewerDiv = $(""#divDocViewer"");
        var w = 0;
        var h = 0;
        var globalToken = """";  // token variable, for current document


        loader.hide();

        if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
            isMobile = true;
        }

        $(window).on(""load"", function () {

            /* Init code for viewer */
            ");



#line 152 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.Raw(ViewBag.ViewerInit));


#line default
#line hidden
                WriteLiteral("\r\n\r\n            globalToken = \'");



#line 154 "..\..\Views\DocoNut\Index.cshtml"
                Write(ViewBag.globalToken);


#line default
#line hidden
                WriteLiteral("\';\r\n            showwatermark = \'");



#line 155 "..\..\Views\DocoNut\Index.cshtml"
                Write(Request.QueryString["showwatermark"]);


#line default
#line hidden
                WriteLiteral(@"';
            $('#_hdnToken').val(globalToken);
            Resize();
        });

        $(window).resize(function () {
            Resize();
        });

        if (isMobile) {
            $(window).on(""orientationchange"", function (event) { Resize(event.orientation); });
        }
        else {
            $(window).on(""resize"", function () { Resize(); });
        }

    </script>

");



#line 173 "..\..\Views\DocoNut\Index.cshtml"

                string host = HttpContext.Current.Request.Url.Host;
                string applicationPath = HttpContext.Current.Request.ApplicationPath + "/";
                string barcodeUri = string.Empty;
                if (Session["BarcodeImgByte"] != null)
                {
                    barcodeUri = Convert.ToBase64String(Session["BarcodeImgByte"] as byte[]);
                }
                string sSignature = string.Empty;
                if (Session["SignatureImage"] != null)
                {
                    sSignature = Convert.ToBase64String(Session["SignatureImage"] as byte[]);
                }
                string sStamp = string.Empty;
                if (Session["StampImage"] != null)
                {
                    sStamp = Convert.ToBase64String(Session["StampImage"] as byte[]);
                }
                string sMessage = string.Empty;
                if (Session["MessageSignatureImage"] != null)
                {
                    sMessage = Convert.ToBase64String(Session["MessageSignatureImage"] as byte[]);
                }



#line default
#line hidden
                WriteLiteral("\r\n    <script>\r\n        var host = \'");



#line 194 "..\..\Views\DocoNut\Index.cshtml"
                Write(host);


#line default
#line hidden
                WriteLiteral("\'\r\n        var applicationPath = \'");



#line 195 "..\..\Views\DocoNut\Index.cshtml"
                Write(applicationPath);


#line default
#line hidden
                WriteLiteral("\';\r\n        var rootPath = \'");



#line 196 "..\..\Views\DocoNut\Index.cshtml"
                Write(host);


#line default
#line hidden
                WriteLiteral("\' + \'");



#line 196 "..\..\Views\DocoNut\Index.cshtml"
                Write(applicationPath);


#line default
#line hidden
                WriteLiteral("\';\r\n        var GetImagePathUrl = \'");



#line 197 "..\..\Views\DocoNut\Index.cshtml"
                Write(Url.Action("GetImagePath", "DocoNut"));


#line default
#line hidden
                WriteLiteral("\';\r\n        var DeleteImageFileUrl = \'");



#line 198 "..\..\Views\DocoNut\Index.cshtml"
                Write(Url.Action("DeleteImageFile", "DocoNut"));


#line default
#line hidden
                WriteLiteral("\';\r\n        var signatureUri = \'");



#line 199 "..\..\Views\DocoNut\Index.cshtml"
                Write(sSignature);


#line default
#line hidden
                WriteLiteral("\';\r\n        var stampUri = \'");



#line 200 "..\..\Views\DocoNut\Index.cshtml"
                Write(sStamp);


#line default
#line hidden
                WriteLiteral("\';\r\n        var barcodeUri = \'");



#line 201 "..\..\Views\DocoNut\Index.cshtml"
                Write(barcodeUri);
#line default
#line hidden
                WriteLiteral("\';\r\n        var messageUri = \'");



#line 204 "..\..\Views\DocoNut\Index.cshtml"
                Write(sMessage);

#line default
#line hidden
                WriteLiteral("\';\r\n        var imageName = \"");



#line 202 "..\..\Views\DocoNut\Index.cshtml"
                Write(Session["UserName" as string]);


#line default
#line hidden
                WriteLiteral("\";\r\n        var urlScheme = \"");



#line 203 "..\..\Views\DocoNut\Index.cshtml"
                Write(Session["UrlSchema" as string]);


#line default
#line hidden
                WriteLiteral(@""";
        var barcodeToken = '';
        var barcodeTokenPath = ""GetBarcodeToken.ashx"";
        var barcodePath = ""GetBarcode.ashx"";
        var signToken = '';
        var signTokenPath = ""AuthSign.ashx"";
        var signPath = ""getSign.ashx"";
    </script>
    <!-- All viewer related scripts -->
    <script src=""");



#line 212 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.viewer.js"));


#line default
#line hidden
                WriteLiteral("\"></script>\r\n\r\n    <!-- All annnotation related scripts -->\r\n    <script src=\"");



#line 215 "..\..\Views\DocoNut\Index.cshtml"
                Write(Html.GetWebResourceUrl("MCS.DoconutMVC.Scripts.annotations.js"));


#line default
#line hidden
                WriteLiteral("\"></script>\r\n");


            });

            WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
