#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DocoNut/Print.cshtml")]
    public partial class _Views_DocoNut_Print_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DocoNut_Print_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");


            
            #line 2 "..\..\Views\DocoNut\Print.cshtml"
  
    ViewBag.Title = "Annotations - Doconut Asp.Net MVC Document Viewer";
    Layout = "~/Views/Shared/doconut/_Layout.cshtml";


            
            #line default
            #line hidden
WriteLiteral(@"<!DOCTYPE html>
<html xmlns=""http://www.w3.org/1999/xhtml"">
<head id=""Head1"" runat=""server"">
    <title></title>
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"" />
    <style type=""text/css"">

        body {
            font-size: 12px;
            font-family: Verdana;
        }

        #divPrint {
            display: none;
        }

        ");


WriteLiteral(@"@media print {
            #non-printable {
                display: none;
            }

            #dvCloseBtn {
                display: none;
            }

            #divPrint {
                display: block;
            }
        }

        #img {
            float: left;
        }

        #divProgress {
            margin-top: 5px;
            background-color: #79B933;
            height: 20px;
            width: 250px;
            text-align: center;
            color: white
        }

        input, select {
            border: solid 1px #CDCDCD;
            font-size: 12px;
            font-family: Verdana;
        }

        /* You can define your own, Adjust values for page margins */

        .A4Page {
            width: 8.3in;
            height: 11.7in;
        }

        .LegalPage {
            width: 7.5in;
            height: 13in;
        }
    </style>
</head>
<body>
    <form id=""form1"" runat=""server"">
        <div id=""non-printable"">
            <table style=""width: 100%"">
                ");



WriteLiteral(@"
                <tr>
                    <td colspan=""2""><div id=""divProgress"" style=""width: 90%"">&nbsp;</div></td>
                </tr>
            </table>

        </div>
        <div id=""dvCloseBtn"">

        </div>
        <div id=""divPrint"">

        </div>
    </form>
    <script type=""text/javascript"" language=""javascript"">

        var totalp = 0;
        var steps = 1;
        var pageFrom = 0;
        var pageTo = 0;
        var pageZoom = 0;
        var token = """";
        var objdivPrint = null;

        function PrintPages(from, to, zoom) {
            if (from > to) {
                alert(""wrong page range"");
                return;
            }
            totalp = 0;

            pageFrom = from;
            pageTo = to;
            pageZoom = zoom;

            ");



WriteLiteral("\r\n            token = getQueryVariable(\"token\");\r\n\r\n            steps = Math.ceil" +
"(parseInt($(\"#divProgress\").width())) / ((to - from) + 1);\r\n\r\n            docume" +
"nt.getElementById(\"divProgress\").style.visibility = \"visible\";\r\n            docu" +
"ment.getElementById(\"divProgress\").style.width = \"0px\";\r\n\r\n            // code t" +
"o rotate the pages\r\n            //if ($(\"#chkLandscape\").prop(\'checked\')) {\r\n\r\n " +
"           //    for (var j = from; j <= to; j++) {\r\n            //        $.pos" +
"t(\"/\" + basePath + \"/DocImage.axd?token=\" + token + \"&zoom=\" + pageZoom + \"&acti" +
"on=1&rotate=90&page=\" + j, function (data) { });\r\n            //    }\r\n\r\n       " +
"     //    sleep(5);\r\n            //}\r\n\r\n\r\n            for (var i = from; i <= t" +
"o; i++) {\r\n                var pgImg = document.createElement(\"IMG\");\r\n         " +
"       pgImg.id = \"img\" + i;\r\n\r\n\r\n                pgImg.src = \"/\" + basePath + \"" +
"/DocImage.axd?token=\" + token + \"&zoom=\" + zoom + \"&page=\" + i;\r\n               " +
" // If you don\'t want to print annotations then..  + \"&AnnMode=1\";\r\n            " +
"    pgImg.className = \"A4Page\";\r\n\r\n                objdivPrint.appendChild(pgImg" +
");\r\n                pgImg.onload = function () { LoadCount((pageTo - pageFrom) +" +
" 1) };\r\n            }\r\n\r\n        }\r\n\r\n        function sleep(seconds) {\r\n       " +
"     var e = new Date().getTime() + (seconds * 1000);\r\n            while (new Da" +
"te().getTime() <= e) { }\r\n        }\r\n\r\n        function LoadCount(t) {\r\n\r\n      " +
"      totalp = totalp + 1;\r\n            document.getElementById(\"divProgress\").s" +
"tyle.width = parseInt($(\"#divProgress\").width()) + steps + \"px\";\r\n            do" +
"cument.getElementById(\"divProgress\").innerHTML = \"Page \" + totalp;\r\n\r\n          " +
"  if (totalp === t) {\r\n\r\n                $(\'#non-printable\').remove();  // Fix f" +
"or IE 9\r\n\r\n                setTimeout(\"self.focus(); window.print(); \", 2000);\r\n" +
"            }\r\n        }\r\n\r\n        function DoPrint() {\r\n\r\n            objdivPr" +
"int = document.getElementById(\"divPrint\");\r\n\r\n            var startPage = 1;\r\n  " +
"          var endPage = getQueryVariable(\"printtotal\");\r\n            var zoomLev" +
"el = 100;\r\n\r\n            PrintPages(startPage, endPage, zoomLevel);\r\n\r\n         " +
"   setTimeout(function () { window.close(); }, 100000);\r\n\r\n            setTimeout" +
"(function () {\r\n                var closeBtn = document.createElement(\"INPUT\");\r" +
"\n                closeBtn.setAttribute(\"type\", \"button\");\r\n                close" +
"Btn.setAttribute(\"id\", \"CloseBtn\");\r\n                closeBtn.setAttribute(\"valu" +
"e\", \"إغلاق\");\r\n                closeBtn.setAttribute(\"onclick\", \"CloseWindow();\"" +
");\r\n                document.getElementById(\"dvCloseBtn\").appendChild(closeBtn);" +
"\r\n            }, 3000);\r\n\r\n        }\r\n\r\n        function CloseWindow() {\r\n      " +
"      window.close();\r\n        }\r\n\r\n        function ClearControls() {\r\n        " +
"    var x = objdivPrint.childNodes.length;\r\n\r\n            for (i = x - 1; i > -1" +
"; i--) {\r\n                if (\'undefined\' != objdivPrint.childNodes[i].id) {\r\n  " +
"                  var objToRemove = document.getElementById(objdivPrint.childNod" +
"es[i].id);\r\n                    if (null != objToRemove) {\r\n                    " +
"    objdivPrint.removeChild(objToRemove);\r\n                    }\r\n              " +
"  }\r\n            }\r\n        }\r\n\r\n        function getQueryVariable(variable) {\r\n" +
"            var query = window.location.search.substring(1);\r\n            var va" +
"rs = query.split(\"&\");\r\n            for (var i = 0; i < vars.length; i++) {\r\n   " +
"             var pair = vars[i].split(\"=\");\r\n                if (pair[0] == vari" +
"able) {\r\n                    return pair[1];\r\n                }\r\n            }\r\n" +
"        }\r\n\r\n        var p = getQueryVariable(\"printpage\");\r\n        if (typeof " +
"(p) != \"undefined\") {\r\n            document.getElementById(\"non-printable\").styl" +
"e.display = \"none\";\r\n            var zoom = getQueryVariable(\"printzoom\");\r\n\r\n  " +
"          if (typeof (zoom) == \"undefined\") {\r\n                zoom = \"100\";\r\n  " +
"          }\r\n\r\n            PrintPages(p, p, zoom);\r\n        }\r\n        else {\r\n " +
"           //document.getElementById(\"txtTo\").value = getQueryVariable(\"printtot" +
"al\");\r\n            document.getElementById(\"divProgress\").style.visibility = \"hi" +
"dden\";\r\n        }\r\n\r\n\r\n\r\n        $(document).ready(function () {\r\n            Do" +
"Print();\r\n        });\r\n    </script>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
