//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Framework.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCS.Framework.Localization.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string must be passed to the constructor.
        /// </summary>
        public static string AConnectionStringMustBePassedToTheConstructor {
            get {
                return ResourceManager.GetString("AConnectionStringMustBePassedToTheConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in your Application.
        /// </summary>
        public static string An_error_occurred_in_your_Application {
            get {
                return ResourceManager.GetString("An_error_occurred_in_your_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in your Application.
        /// </summary>
        public static string AnErrorOccurredInYourApplication {
            get {
                return ResourceManager.GetString("AnErrorOccurredInYourApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap output returned must specify a Content type. For example: [CallbackMethod(ContentType=&quot;image/png&quot;)].
        /// </summary>
        public static string BitmapOutputReturnedMustSpecifyAContentType {
            get {
                return ResourceManager.GetString("BitmapOutputReturnedMustSpecifyAContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte[] value greater than 20megs are not supported.
        /// </summary>
        public static string ByteValueGreaterThan20megsAreNotSupported {
            get {
                return ResourceManager.GetString("ByteValueGreaterThan20megsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save resource: Invalid culture id passed: {0}.
        /// </summary>
        public static string Can_t_save_resource__Invalid_culture_id_passed {
            get {
                return ResourceManager.GetString("Can_t_save_resource__Invalid_culture_id_passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get values if AllowUpdates is not set to true.
        /// </summary>
        public static string CanTGetValuesIfAllowUpdatesIsNotSetToTrue {
            get {
                return ResourceManager.GetString("CanTGetValuesIfAllowUpdatesIsNotSetToTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t retrieve items in update mode .
        /// </summary>
        public static string CanTRetrieveItemsInUpdateMode {
            get {
                return ResourceManager.GetString("CanTRetrieveItemsInUpdateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id and Client Secret must be provided..
        /// </summary>
        public static string Client_Id_and_Client_Secret_must_be_provided {
            get {
                return ResourceManager.GetString("Client_Id_and_Client_Secret_must_be_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id and Client Secret must be provided..
        /// </summary>
        public static string Client_Id_and_Client_Secret_must_be_provided_ {
            get {
                return ResourceManager.GetString("Client_Id_and_Client_Secret_must_be_provided_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Configuration method is no longer supported. Use a Provider configuration instead..
        /// </summary>
        public static string ConfigurationMethodNoLongerSupported {
            get {
                return ResourceManager.GetString("ConfigurationMethodNoLongerSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: .
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string for resources is not configured.
        /// </summary>
        public static string ConnectionStringForResourcesIsNotConfigure {
            get {
                return ResourceManager.GetString("ConnectionStringForResourcesIsNotConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load entity - invalid key provided..
        /// </summary>
        public static string CouldntLoadEntityInvalidKeyProvided {
            get {
                return ResourceManager.GetString("CouldntLoadEntityInvalidKeyProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataReader passed to DataReaderToObject cannot be closed.
        /// </summary>
        public static string DataReaderPassedToDataReaderToObjectCannot {
            get {
                return ResourceManager.GetString("DataReaderPassedToDataReaderToObjectCannot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page Resources.
        /// </summary>
        public static string EditPageResources {
            get {
                return ResourceManager.GetString("EditPageResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to call a Wcf or ASMX service you have to specify ClientProxyTargetType of the Web Service instance..
        /// </summary>
        public static string ERROR_CLASSWRAPPER_FORWCFASMX_REQUIRES_CLIENTPROXYTYPE {
            get {
                return ResourceManager.GetString("ERROR_CLASSWRAPPER_FORWCFASMX_REQUIRES_CLIENTPROXYTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON string input..
        /// </summary>
        public static string ERROR_INVALID_JSON_STRING {
            get {
                return ResourceManager.GetString("ERROR_INVALID_JSON_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one ScriptContainer is allowed per page..
        /// </summary>
        public static string ERROR_ONLYONE_SCRIPTCONTAINER_PER_PAGE_ALLOWED {
            get {
                return ResourceManager.GetString("ERROR_ONLYONE_SCRIPTCONTAINER_PER_PAGE_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScriptContainer.Current only works with Page based handlers..
        /// </summary>
        public static string ERROR_ScriptContainer_OnlyWorks_With_PageBasedHandlers {
            get {
                return ResourceManager.GetString("ERROR_ScriptContainer_OnlyWorks_With_PageBasedHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert content type {0} to ImageFormat.
        /// </summary>
        public static string ERROR_UnableToConvertContentTypeToImageFormat {
            get {
                return ResourceManager.GetString("ERROR_UnableToConvertContentTypeToImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to convert ImageFormat {0} to ContentType.
        /// </summary>
        public static string ERROR_UnableToConvertImageFormatToContentType {
            get {
                return ResourceManager.GetString("ERROR_UnableToConvertImageFormatToContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string ErrorColon {
            get {
                return ResourceManager.GetString("ErrorColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid BindingSource.
        /// </summary>
        public static string InvalidBindingSource {
            get {
                return ResourceManager.GetString("InvalidBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection String..
        /// </summary>
        public static string InvalidConnectionString {
            get {
                return ResourceManager.GetString("InvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection string name..
        /// </summary>
        public static string InvalidConnectionStringName {
            get {
                return ResourceManager.GetString("InvalidConnectionStringName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Control.
        /// </summary>
        public static string InvalidControl {
            get {
                return ResourceManager.GetString("InvalidControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Control Id.
        /// </summary>
        public static string InvalidControlId {
            get {
                return ResourceManager.GetString("InvalidControlId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex digit: .
        /// </summary>
        public static string InvalidHexDigit {
            get {
                return ResourceManager.GetString("InvalidHexDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hex string length: {0}.
        /// </summary>
        public static string InvalidHexStringLength {
            get {
                return ResourceManager.GetString("InvalidHexStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search result..
        /// </summary>
        public static string InvalidSearchResult {
            get {
                return ResourceManager.GetString("InvalidSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Server Method..
        /// </summary>
        public static string InvalidServerMethod {
            get {
                return ResourceManager.GetString("InvalidServerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type for XmlType to .NET Type conversion..
        /// </summary>
        public static string InvalidTypeForXmlTypeToNETTypeConversion {
            get {
                return ResourceManager.GetString("InvalidTypeForXmlTypeToNETTypeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL: Virtual path relative URL (~) not allowed when HttpContext not available..
        /// </summary>
        public static string InvalidURLRelativeURLNotAllowed {
            get {
                return ResourceManager.GetString("InvalidURLRelativeURLNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Options.
        /// </summary>
        public static string LocalizationOptions {
            get {
                return ResourceManager.GetString("LocalizationOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Table exists already.
        /// </summary>
        public static string LocalizationTable_Localization_Table_exists_already {
            get {
                return ResourceManager.GetString("LocalizationTable_Localization_Table_exists_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching Recordset found..
        /// </summary>
        public static string No_matching_Recordset_found_ {
            get {
                return ResourceManager.GetString("No_matching_Recordset_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ResourceId specified. Can&apos;t add resource.
        /// </summary>
        public static string NoResourceIdSpecifiedCantAddResource {
            get {
                return ResourceManager.GetString("NoResourceIdSpecifiedCantAddResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed. Method expects {0}..
        /// </summary>
        public static string NotAllowedMethodExpectsVerb {
            get {
                return ResourceManager.GetString("NotAllowedMethodExpectsVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object could not be deserialized from Xml..
        /// </summary>
        public static string ObjectCouldNotBeDeserializedFromXml {
            get {
                return ResourceManager.GetString("ObjectCouldNotBeDeserializedFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server method is not accessible due to missing CallbackMethod attribute.
        /// </summary>
        public static string ServerMethodIsNotAccessibleDueToMissing {
            get {
                return ResourceManager.GetString("ServerMethodIsNotAccessibleDueToMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Localization Icons.
        /// </summary>
        public static string ShowLocalizationIcons {
            get {
                return ResourceManager.GetString("ShowLocalizationIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Conversion not handled in StringToTypedValue for.
        /// </summary>
        public static string StringToTypedValueValueTypeConversionFailed {
            get {
                return ResourceManager.GetString("StringToTypedValueValueTypeConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Conversion not handled in StringToTypedValue for .
        /// </summary>
        public static string StringToTypedValueValueTypeConversionFailed1 {
            get {
                return ResourceManager.GetString("StringToTypedValueValueTypeConversionFailed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read configuration string from Sql Server field..
        /// </summary>
        public static string UnableToExtractKeys {
            get {
                return ResourceManager.GetString("UnableToExtractKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read config information from string..
        /// </summary>
        public static string UnableToReadConfigDataFromString {
            get {
                return ResourceManager.GetString("UnableToReadConfigDataFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported JSON Serializer specified. Json.Net and System.Web.Extensions must be explicitly compiled in..
        /// </summary>
        public static string UnsupportedJSONSerializerSpecified {
            get {
                return ResourceManager.GetString("UnsupportedJSONSerializerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebResource not available for jQuery UI.
        /// </summary>
        public static string WebResourceNotAvailableForJQueryUI {
            get {
                return ResourceManager.GetString("WebResourceNotAvailableForJQueryUI", resourceCulture);
            }
        }
    }
}
