//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCS.Integration.HUB.CSIAgencyOutboundServicesRef
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", ConfigurationName = "CSIAgencyOutboundServicesRef.CSIAgencyOutboundServicesInterface")]
    public interface CSIAgencyOutboundServicesInterface
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundSend", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendResponse OutboundSend(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundSend", ReplyAction = "*")]
        System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendResponse> OutboundSendAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundReject", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectResponse OutboundReject(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundReject", ReplyAction = "*")]
        System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectResponse> OutboundRejectAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundStatusInquiry", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryResponse OutboundStatusInquiry(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1/ICSIAgencyOutbound" +
            "Services/OutboundStatusInquiry", ReplyAction = "*")]
        System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryResponse> OutboundStatusInquiryAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1")]
    public partial class SendOutboundOutboundRec : object, System.ComponentModel.INotifyPropertyChanged
    {

        private SendOutboundOutboundRecOutboundInfo outboundInfoField;

        private SendOutboundOutboundRecRoutingInfo routingInfoField;

        private SendOutboundOutboundRecAttachmentRec[] attachmentRecField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SendOutboundOutboundRecOutboundInfo OutboundInfo
        {
            get
            {
                return this.outboundInfoField;
            }
            set
            {
                this.outboundInfoField = value;
                this.RaisePropertyChanged("OutboundInfo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SendOutboundOutboundRecRoutingInfo RoutingInfo
        {
            get
            {
                return this.routingInfoField;
            }
            set
            {
                this.routingInfoField = value;
                this.RaisePropertyChanged("RoutingInfo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentRec", Order = 2)]
        public SendOutboundOutboundRecAttachmentRec[] AttachmentRec
        {
            get
            {
                return this.attachmentRecField;
            }
            set
            {
                this.attachmentRecField = value;
                this.RaisePropertyChanged("AttachmentRec");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1")]
    public partial class SendOutboundOutboundRecOutboundInfo : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string outboundDocNoField;

        private Msg_Subject outboundTypeField;

        private System.DateTime outboundGDateField;

        private string outboundHDateField;

        private string outboundSubjectField;

        private OutboundCategory_Type outboundCategoryField;

        private string outboundRemarksField;

        private string sPTrackingNumberField;

        private string outboundHDueDateField;

        private System.DateTime outboundGDueDateField;

        private bool outboundGDueDateFieldSpecified;

        private OutboundClassification_Type outboundClassificationField;

        private SendOutboundOutboundRecOutboundInfoRelatedPersonsInfo[] relatedPersonsInfoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string OutboundDocNo
        {
            get
            {
                return this.outboundDocNoField;
            }
            set
            {
                this.outboundDocNoField = value;
                this.RaisePropertyChanged("OutboundDocNo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public Msg_Subject OutboundType
        {
            get
            {
                return this.outboundTypeField;
            }
            set
            {
                this.outboundTypeField = value;
                this.RaisePropertyChanged("OutboundType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime OutboundGDate
        {
            get
            {
                return this.outboundGDateField;
            }
            set
            {
                this.outboundGDateField = value;
                this.RaisePropertyChanged("OutboundGDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string OutboundHDate
        {
            get
            {
                return this.outboundHDateField;
            }
            set
            {
                this.outboundHDateField = value;
                this.RaisePropertyChanged("OutboundHDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string OutboundSubject
        {
            get
            {
                return this.outboundSubjectField;
            }
            set
            {
                this.outboundSubjectField = value;
                this.RaisePropertyChanged("OutboundSubject");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public OutboundCategory_Type OutboundCategory
        {
            get
            {
                return this.outboundCategoryField;
            }
            set
            {
                this.outboundCategoryField = value;
                this.RaisePropertyChanged("OutboundCategory");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string OutboundRemarks
        {
            get
            {
                return this.outboundRemarksField;
            }
            set
            {
                this.outboundRemarksField = value;
                this.RaisePropertyChanged("OutboundRemarks");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string SPTrackingNumber
        {
            get
            {
                return this.sPTrackingNumberField;
            }
            set
            {
                this.sPTrackingNumberField = value;
                this.RaisePropertyChanged("SPTrackingNumber");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string OutboundHDueDate
        {
            get
            {
                return this.outboundHDueDateField;
            }
            set
            {
                this.outboundHDueDateField = value;
                this.RaisePropertyChanged("OutboundHDueDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public System.DateTime OutboundGDueDate
        {
            get
            {
                return this.outboundGDueDateField;
            }
            set
            {
                this.outboundGDueDateField = value;
                this.RaisePropertyChanged("OutboundGDueDate");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutboundGDueDateSpecified
        {
            get
            {
                return this.outboundGDueDateFieldSpecified;
            }
            set
            {
                this.outboundGDueDateFieldSpecified = value;
                this.RaisePropertyChanged("OutboundGDueDateSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public OutboundClassification_Type OutboundClassification
        {
            get
            {
                return this.outboundClassificationField;
            }
            set
            {
                this.outboundClassificationField = value;
                this.RaisePropertyChanged("OutboundClassification");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelatedPersonsInfo", Order = 11)]
        public SendOutboundOutboundRecOutboundInfoRelatedPersonsInfo[] RelatedPersonsInfo
        {
            get
            {
                return this.relatedPersonsInfoField;
            }
            set
            {
                this.relatedPersonsInfoField = value;
                this.RaisePropertyChanged("RelatedPersonsInfo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Msg_Subject
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("48")]
        Item48,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum OutboundCategory_Type
    {

        /// <remarks/>
        Financial,
        /// <remarks/>
        Management,
        /// <remarks/>
        Judicial,
        /// <remarks/>
        Penal,
        /// <remarks/>
        General,
        /// <remarks/>
        Ministerial,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum OutboundClassification_Type
    {

        /// <remarks/>
        Original,

        /// <remarks/>
        Copy,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1")]
    public partial class SendOutboundOutboundRecOutboundInfoRelatedPersonsInfo : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string personFullNameField;

        private string personIDField;

        private string personAddressField;

        private string personEmailField;

        private string personMobileNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string PersonFullName
        {
            get
            {
                return this.personFullNameField;
            }
            set
            {
                this.personFullNameField = value;
                this.RaisePropertyChanged("PersonFullName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string PersonID
        {
            get
            {
                return this.personIDField;
            }
            set
            {
                this.personIDField = value;
                this.RaisePropertyChanged("PersonID");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string PersonAddress
        {
            get
            {
                return this.personAddressField;
            }
            set
            {
                this.personAddressField = value;
                this.RaisePropertyChanged("PersonAddress");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string PersonEmail
        {
            get
            {
                return this.personEmailField;
            }
            set
            {
                this.personEmailField = value;
                this.RaisePropertyChanged("PersonEmail");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string PersonMobileNumber
        {
            get
            {
                return this.personMobileNumberField;
            }
            set
            {
                this.personMobileNumberField = value;
                this.RaisePropertyChanged("PersonMobileNumber");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1")]
    public partial class SendOutboundOutboundRecRoutingInfo : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string fromField;

        private string toField;

        private Msg_Secrecy secrecyLevelField;

        private Msg_Priority priorityField;

        private OutboundDelivery_Type deliveryTypeField;

        private OutboundSender_Type senderTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public Msg_Secrecy SecrecyLevel
        {
            get
            {
                return this.secrecyLevelField;
            }
            set
            {
                this.secrecyLevelField = value;
                this.RaisePropertyChanged("SecrecyLevel");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public Msg_Priority Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public OutboundDelivery_Type DeliveryType
        {
            get
            {
                return this.deliveryTypeField;
            }
            set
            {
                this.deliveryTypeField = value;
                this.RaisePropertyChanged("DeliveryType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public OutboundSender_Type SenderType
        {
            get
            {
                return this.senderTypeField;
            }
            set
            {
                this.senderTypeField = value;
                this.RaisePropertyChanged("SenderType");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Msg_Secrecy
    {

        /// <remarks/>
        S,

        /// <remarks/>
        TS,

        /// <remarks/>
        N,

        /// <remarks/>
        NN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Msg_Priority
    {

        /// <remarks/>
        L,

        /// <remarks/>
        N,

        /// <remarks/>
        H,

        /// <remarks/>
        C,

        /// <remarks/>
        I,

        /// <remarks/>
        BH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum OutboundDelivery_Type
    {

        /// <remarks/>
        M,

        /// <remarks/>
        E,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum OutboundSender_Type
    {

        /// <remarks/>
        GOVT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1")]
    public partial class SendOutboundOutboundRecAttachmentRec : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string attachmentIdField;

        private byte[] attachmentBase64Field;

        private string remarksField;

        private Attachment_Type attachementTypeField;

        private AttachmentContent_Type attachmentContentTypeField;

        private string attachmentFileNameField;

        private string attachementURLField;

        private bool isObjectField;

        private byte[] attachmentBarcodeField;

        private Content_Classification contentClassificationField;

        private bool contentClassificationFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string AttachmentId
        {
            get
            {
                return this.attachmentIdField;
            }
            set
            {
                this.attachmentIdField = value;
                this.RaisePropertyChanged("AttachmentId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 1)]
        public byte[] AttachmentBase64
        {
            get
            {
                return this.attachmentBase64Field;
            }
            set
            {
                this.attachmentBase64Field = value;
                this.RaisePropertyChanged("AttachmentBase64");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
                this.RaisePropertyChanged("Remarks");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public Attachment_Type AttachementType
        {
            get
            {
                return this.attachementTypeField;
            }
            set
            {
                this.attachementTypeField = value;
                this.RaisePropertyChanged("AttachementType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public AttachmentContent_Type AttachmentContentType
        {
            get
            {
                return this.attachmentContentTypeField;
            }
            set
            {
                this.attachmentContentTypeField = value;
                this.RaisePropertyChanged("AttachmentContentType");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string AttachmentFileName
        {
            get
            {
                return this.attachmentFileNameField;
            }
            set
            {
                this.attachmentFileNameField = value;
                this.RaisePropertyChanged("AttachmentFileName");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string AttachementURL
        {
            get
            {
                return this.attachementURLField;
            }
            set
            {
                this.attachementURLField = value;
                this.RaisePropertyChanged("AttachementURL");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool IsObject
        {
            get
            {
                return this.isObjectField;
            }
            set
            {
                this.isObjectField = value;
                this.RaisePropertyChanged("IsObject");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary", Order = 8)]
        public byte[] AttachmentBarcode
        {
            get
            {
                return this.attachmentBarcodeField;
            }
            set
            {
                this.attachmentBarcodeField = value;
                this.RaisePropertyChanged("AttachmentBarcode");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public Content_Classification ContentClassification
        {
            get
            {
                return this.contentClassificationField;
            }
            set
            {
                this.contentClassificationField = value;
                this.RaisePropertyChanged("ContentClassification");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContentClassificationSpecified
        {
            get
            {
                return this.contentClassificationFieldSpecified;
            }
            set
            {
                this.contentClassificationFieldSpecified = value;
                this.RaisePropertyChanged("ContentClassificationSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Attachment_Type
    {

        /// <remarks/>
        MAIN,
        /// <remarks/>
        SUB,
        /// <remarks/>
        COPY,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum AttachmentContent_Type
    {

        /// <remarks/>
        PNG,
        /// <remarks/>
        JPEG,
        /// <remarks/>
        BMP,
        /// <remarks/>
        GIF,
        /// <remarks/>
        PDF,
        /// <remarks/>
        TIF,
        /// <remarks/>
        DOC,
        /// <remarks/>
        DOCX,
        /// <remarks/>
        XLS,
        /// <remarks/>
        XLSX,
        /// <remarks></remarks>
        OBJ,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Content_Classification
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("48")]
        Item48,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("57")]
        Item57,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("59")]
        Item59,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68")]
        Item68,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("74")]
        Item74,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("76")]
        Item76,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("77")]
        Item77,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("78")]
        Item78,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum Status_Type
    {

        /// <remarks/>
        Success,

        /// <remarks/>
        Failed,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SendOutbound", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundSendRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.SendOutboundOutboundRec OutboundRec;

        public OutboundSendRequest()
        {
        }

        public OutboundSendRequest(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.SendOutboundOutboundRec OutboundRec)
        {
            this.OutboundRec = OutboundRec;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "SendOutboundResponse", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundSendResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.Status_Type Status;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 1)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 2)]
        public string ErrorMessage;

        public OutboundSendResponse()
        {
        }

        public OutboundSendResponse(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.Status_Type Status, string ErrorCode, string ErrorMessage)
        {
            this.Status = Status;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RejectOutbound", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundRejectRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public string From;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 1)]
        public string To;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 2)]
        public string OutboundDocumentNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 3)]
        public System.DateTime RejectionDate;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 4)]
        public string RejectionCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 5)]
        public string RejectionReason;

        public OutboundRejectRequest()
        {
        }

        public OutboundRejectRequest(string From, string To, string OutboundDocumentNumber, System.DateTime RejectionDate, string RejectionCode, string RejectionReason)
        {
            this.From = From;
            this.To = To;
            this.OutboundDocumentNumber = OutboundDocumentNumber;
            this.RejectionDate = RejectionDate;
            this.RejectionCode = RejectionCode;
            this.RejectionReason = RejectionReason;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "RejectOutboundResponse", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundRejectResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.Status_Type Status;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 1)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 2)]
        public string ErrorMessage;

        public OutboundRejectResponse()
        {
        }

        public OutboundRejectResponse(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.Status_Type Status, string ErrorCode, string ErrorMessage)
        {
            this.Status = Status;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://yefi.gov.sa/CSIHUBDataTypes/xml/schemas/version1.0")]
    public enum MsgStatus_Type
    {

        /// <remarks/>
        Pending,

        /// <remarks/>
        Accepted,

        /// <remarks/>
        Rejected,

        /// <remarks/>
        NotFound,

        /// <remarks/>
        Failed,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "StatusInquiry", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundStatusInquiryRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public string From;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 1)]
        public string To;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 2)]
        public string OutboundDocumentNumber;

        public OutboundStatusInquiryRequest()
        {
        }

        public OutboundStatusInquiryRequest(string From, string To, string OutboundDocumentNumber)
        {
            this.From = From;
            this.To = To;
            this.OutboundDocumentNumber = OutboundDocumentNumber;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "StatusInquiryResponse", WrapperNamespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", IsWrapped = true)]
    public partial class OutboundStatusInquiryResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 0)]
        public string OutboundDocumentNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 1)]
        public string InboundDocumentNumber;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 2)]
        public string InboundCreationTimestamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 3)]
        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.MsgStatus_Type Status;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 4)]
        public System.DateTime Timestamp;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 5)]
        public string ErrorCode;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://yesser.gov.sa/NCS/CSIAgencyOutboundServices/version/0.1", Order = 6)]
        public string ErrorMessage;

        public OutboundStatusInquiryResponse()
        {
        }

        public OutboundStatusInquiryResponse(string OutboundDocumentNumber, string InboundDocumentNumber, string InboundCreationTimestamp, MCS.Integration.HUB.CSIAgencyOutboundServicesRef.MsgStatus_Type Status, System.DateTime Timestamp, string ErrorCode, string ErrorMessage)
        {
            this.OutboundDocumentNumber = OutboundDocumentNumber;
            this.InboundDocumentNumber = InboundDocumentNumber;
            this.InboundCreationTimestamp = InboundCreationTimestamp;
            this.Status = Status;
            this.Timestamp = Timestamp;
            this.ErrorCode = ErrorCode;
            this.ErrorMessage = ErrorMessage;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CSIAgencyOutboundServicesInterfaceChannel : MCS.Integration.HUB.CSIAgencyOutboundServicesRef.CSIAgencyOutboundServicesInterface, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CSIAgencyOutboundServicesInterfaceClient : System.ServiceModel.ClientBase<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.CSIAgencyOutboundServicesInterface>, MCS.Integration.HUB.CSIAgencyOutboundServicesRef.CSIAgencyOutboundServicesInterface
    {

        public CSIAgencyOutboundServicesInterfaceClient()
        {
        }

        public CSIAgencyOutboundServicesInterfaceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CSIAgencyOutboundServicesInterfaceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CSIAgencyOutboundServicesInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CSIAgencyOutboundServicesInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendResponse OutboundSend(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendRequest request)
        {
            return base.Channel.OutboundSend(request);
        }

        public System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendResponse> OutboundSendAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundSendRequest request)
        {
            return base.Channel.OutboundSendAsync(request);
        }

        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectResponse OutboundReject(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectRequest request)
        {
            return base.Channel.OutboundReject(request);
        }

        public System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectResponse> OutboundRejectAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundRejectRequest request)
        {
            return base.Channel.OutboundRejectAsync(request);
        }

        public MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryResponse OutboundStatusInquiry(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryRequest request)
        {
            return base.Channel.OutboundStatusInquiry(request);
        }

        public System.Threading.Tasks.Task<MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryResponse> OutboundStatusInquiryAsync(MCS.Integration.HUB.CSIAgencyOutboundServicesRef.OutboundStatusInquiryRequest request)
        {
            return base.Channel.OutboundStatusInquiryAsync(request);
        }
    }
}
